from __future__ import annotations

_FOCUSED_EVIDENCE_BY_METHOD: dict[str, tuple[str, ...]] = {
    "connect": ("tests/scenarios/test_startup_sync_fom_java_translation_v09.py",),
    "createFederationExecution": ("tests/factories/test_fom_time_factories.py", "tests/scenarios/test_startup_sync_fom_java_translation_v09.py"),
    "createFederationExecutionWithMIM": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_federation_lifecycle.py::run_federation_lifecycle_scenario",
        "tests/scenarios/test_federation_lifecycle_backend_matrix.py::test_python_backend_federation_lifecycle_with_mim_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_federation_lifecycle_with_mim_matrix",
    ),
    "disconnect": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_federation_lifecycle.py::run_federation_lifecycle_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_resign.py::run_disconnect_mom_cleanup_scenario",
        "tests/scenarios/test_federation_lifecycle_backend_matrix.py::test_python_backend_federation_lifecycle_matrix",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_disconnect_mom_cleanup_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_federation_lifecycle_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_disconnect_mom_cleanup_matrix",
    ),
    "destroyFederationExecution": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_federation_lifecycle.py::run_federation_lifecycle_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_federation_lifecycle.py::run_federation_lifecycle_negative_scenario",
        "tests/scenarios/test_federation_lifecycle_backend_matrix.py::test_python_backend_federation_lifecycle_matrix",
        "tests/scenarios/test_federation_lifecycle_backend_matrix.py::test_python_backend_federation_lifecycle_negative_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_federation_lifecycle_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_federation_lifecycle_negative_matrix",
    ),
    "listFederationExecutions": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_federation_lifecycle.py::run_federation_listing_scenario",
        "tests/scenarios/test_federation_lifecycle_backend_matrix.py::test_python_backend_federation_listing_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_federation_listing_matrix",
    ),
    "reportFederationExecutions": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_federation_lifecycle.py::run_federation_listing_scenario",
        "tests/scenarios/test_federation_lifecycle_backend_matrix.py::test_python_backend_federation_listing_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_federation_listing_matrix",
    ),
    "joinFederationExecution": ("tests/scenarios/test_startup_sync_fom_java_translation_v09.py",),
    "resignFederationExecution": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_resign.py::run_resign_precondition_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_resign.py::run_resign_mom_cleanup_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_save_restore.py::run_resigned_federate_callback_silence_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_resign_precondition_matrix",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_resign_mom_cleanup_matrix",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_resigned_federate_callback_silence_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_resign_precondition_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_resign_mom_cleanup_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_resigned_federate_callback_silence_matrix",
    ),
    "publishObjectClassAttributes": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_declaration.py::run_declaration_management_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_backend_declaration_management_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_declaration_management_matrix",
    ),
    "unpublishObjectClass": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_declaration.py::run_declaration_management_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_backend_declaration_management_overload_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_declaration_management_overload_matrix",
    ),
    "unpublishObjectClassAttributes": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_declaration.py::run_declaration_management_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_backend_declaration_management_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_declaration_management_matrix",
    ),
    "publishInteractionClass": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_declaration.py::run_declaration_management_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_backend_declaration_management_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_declaration_management_matrix",
    ),
    "unpublishInteractionClass": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_declaration.py::run_declaration_management_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_backend_declaration_management_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_declaration_management_matrix",
    ),
    "subscribeObjectClassAttributes": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_declaration.py::run_declaration_management_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_backend_declaration_management_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_declaration_management_matrix",
    ),
    "subscribeObjectClassAttributesPassively": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_declaration.py::run_declaration_management_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_backend_declaration_management_overload_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_declaration_management_overload_matrix",
    ),
    "unsubscribeObjectClass": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_declaration.py::run_declaration_management_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_backend_declaration_management_overload_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_declaration_management_overload_matrix",
    ),
    "unsubscribeObjectClassAttributes": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_declaration.py::run_declaration_management_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_backend_declaration_management_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_declaration_management_matrix",
    ),
    "subscribeInteractionClass": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_declaration.py::run_declaration_management_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_backend_declaration_management_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_declaration_management_matrix",
    ),
    "subscribeInteractionClassPassively": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_declaration.py::run_declaration_management_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_backend_declaration_management_overload_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_declaration_management_overload_matrix",
    ),
    "unsubscribeInteractionClass": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_declaration.py::run_declaration_management_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_backend_declaration_management_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_declaration_management_matrix",
    ),
    "reserveObjectInstanceName": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_name_reservation.py::run_name_reservation_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_name_reservation_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_name_reservation_matrix",
    ),
    "releaseObjectInstanceName": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_name_reservation.py::run_name_reservation_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_name_reservation_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_name_reservation_matrix",
    ),
    "reserveMultipleObjectInstanceName": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_name_reservation.py::run_name_reservation_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_name_reservation_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_name_reservation_matrix",
    ),
    "releaseMultipleObjectInstanceName": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_name_reservation.py::run_name_reservation_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_name_reservation_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_name_reservation_matrix",
    ),
    "registerObjectInstance": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_exchange.py::run_two_federate_exchange_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_backend_exchange_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_exchange_matrix",
    ),
    "deleteObjectInstance": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_exchange.py::run_two_federate_exchange_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_timed_delete.py::run_timed_delete_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_backend_exchange_matrix",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_timed_delete_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_exchange_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_timed_delete_matrix",
    ),
    "localDeleteObjectInstance": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_local_delete.py::run_local_delete_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_local_delete_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_local_delete_matrix",
    ),
    "requestAttributeTransportationTypeChange": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_transportation_type.py::run_transportation_type_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_transportation_type.py::run_transportation_type_restore_persistence_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_transportation_type_matrix",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_transportation_type_restore_persistence_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_transportation_type_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_transportation_type_restore_persistence_matrix",
    ),
    "queryAttributeTransportationType": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_transportation_type.py::run_transportation_type_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_transportation_type.py::run_transportation_type_restore_persistence_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_transportation_type_matrix",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_transportation_type_restore_persistence_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_transportation_type_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_transportation_type_restore_persistence_matrix",
    ),
    "requestInteractionTransportationTypeChange": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_transportation_type.py::run_transportation_type_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_transportation_type.py::run_transportation_type_restore_persistence_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_transportation_type_matrix",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_transportation_type_restore_persistence_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_transportation_type_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_transportation_type_restore_persistence_matrix",
    ),
    "queryInteractionTransportationType": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_transportation_type.py::run_transportation_type_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_transportation_type.py::run_transportation_type_restore_persistence_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_transportation_type_matrix",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_transportation_type_restore_persistence_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_transportation_type_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_transportation_type_restore_persistence_matrix",
    ),
    "registerFederationSynchronizationPoint": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_sync.py::run_synchronization_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_sync.py::run_synchronization_registration_failure_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_synchronization_matrix",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_synchronization_registration_failure_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_synchronization_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_synchronization_registration_failure_matrix",
    ),
    "synchronizationPointRegistrationSucceeded": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_sync.py::run_synchronization_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_sync.py::run_synchronization_registration_failure_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_synchronization_matrix",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_synchronization_registration_failure_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_synchronization_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_synchronization_registration_failure_matrix",
    ),
    "synchronizationPointRegistrationFailed": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_sync.py::run_synchronization_registration_failure_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_synchronization_registration_failure_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_synchronization_registration_failure_matrix",
    ),
    "announceSynchronizationPoint": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_sync.py::run_synchronization_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_synchronization_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_synchronization_matrix",
    ),
    "synchronizationPointAchieved": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_sync.py::run_synchronization_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_synchronization_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_synchronization_matrix",
    ),
    "federationSynchronized": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_sync.py::run_synchronization_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_sync.py::run_failed_federate_synchronization_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_synchronization_matrix",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_failed_federate_synchronization_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_synchronization_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_failed_federate_synchronization_matrix",
    ),
    "requestFederationSave": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_save_restore.py::run_save_restore_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_save_restore.py::run_save_abort_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_save_restore_matrix",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_save_abort_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_save_restore_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_save_abort_matrix",
    ),
    "initiateFederateSave": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_save_restore.py::run_save_restore_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_save_restore_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_save_restore_matrix",
    ),
    "federateSaveBegun": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_save_restore.py::run_save_restore_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_save_restore_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_save_restore_matrix",
    ),
    "federateSaveComplete": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_save_restore.py::run_save_restore_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_save_restore_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_save_restore_matrix",
    ),
    "federateSaveNotComplete": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_save_restore.py::run_save_failure_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_save_failure_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_save_failure_matrix",
    ),
    "abortFederationSave": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_save_restore.py::run_save_abort_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_save_abort_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_save_abort_matrix",
    ),
    "queryFederationSaveStatus": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_save_restore.py::run_save_restore_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_save_restore_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_save_restore_matrix",
    ),
    "federationSaveStatusResponse": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_save_restore.py::run_save_restore_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_save_restore_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_save_restore_matrix",
    ),
    "requestFederationRestore": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_save_restore.py::run_save_restore_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_save_restore.py::run_restore_request_failure_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_save_restore_matrix",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_restore_request_failure_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_save_restore_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_restore_request_failure_matrix",
    ),
    "requestFederationRestoreSucceeded": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_save_restore.py::run_save_restore_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_save_restore_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_save_restore_matrix",
    ),
    "requestFederationRestoreFailed": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_save_restore.py::run_restore_request_failure_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_restore_request_failure_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_restore_request_failure_matrix",
    ),
    "federationRestoreBegun": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_save_restore.py::run_save_restore_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_save_restore_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_save_restore_matrix",
    ),
    "initiateFederateRestore": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_save_restore.py::run_save_restore_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_save_restore_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_save_restore_matrix",
    ),
    "federateRestoreComplete": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_save_restore.py::run_save_restore_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_save_restore_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_save_restore_matrix",
    ),
    "federateRestoreNotComplete": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_save_restore.py::run_restore_failure_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_restore_failure_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_restore_failure_matrix",
    ),
    "abortFederationRestore": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_save_restore.py::run_restore_abort_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_restore_abort_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_restore_abort_matrix",
    ),
    "queryFederationRestoreStatus": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_save_restore.py::run_save_restore_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_save_restore_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_save_restore_matrix",
    ),
    "federationRestored": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_save_restore.py::run_save_restore_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_save_restore_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_save_restore_matrix",
    ),
    "federationNotRestored": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_save_restore.py::run_restore_failure_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_restore_failure_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_restore_failure_matrix",
    ),
    "federationRestoreStatusResponse": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_save_restore.py::run_save_restore_scenario",
        "tests/scenarios/test_federation_management_backend_matrix.py::test_python_backend_save_restore_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_save_restore_matrix",
    ),
    "enableTimeRegulation": ("tests/time/test_mom_mim_time_v10.py", "tests/verification/test_compliance_slice_v011.py"),
    "enableTimeConstrained": (
        "tests/time/test_mom_mim_and_time_semantics_v010.py",
        "tests/verification/test_compliance_slice_v011.py",
    ),
    "disableTimeRegulation": ("tests/time/test_mom_mim_and_time_semantics_v010.py",),
    "disableTimeConstrained": ("tests/time/test_mom_mim_and_time_semantics_v010.py",),
    "timeAdvanceRequest": ("tests/time/test_mom_mim_time_v10.py", "tests/verification/test_compliance_slice_v011.py"),
    "timeAdvanceRequestAvailable": ("tests/time/test_mom_mim_time_v10.py",),
    "nextMessageRequest": ("tests/time/test_mom_mim_time_v10.py",),
    "nextMessageRequestAvailable": (
        "tests/time/test_mom_mim_time_v10.py",
        "tests/verification/test_compliance_slice_v011.py",
    ),
    "flushQueueRequest": ("tests/time/test_mom_mim_time_v10.py",),
    "queryGALT": ("tests/time/test_mom_mim_time_v10.py", "tests/verification/test_compliance_slice_v011.py"),
    "queryLogicalTime": (
        "tests/time/test_mom_mim_and_time_semantics_v010.py",
        "tests/verification/test_compliance_slice_v011.py",
    ),
    "queryLITS": ("tests/time/test_mom_mim_time_v10.py", "tests/verification/test_compliance_slice_v011.py"),
    "modifyLookahead": (
        "tests/time/test_mom_mim_and_time_semantics_v010.py",
        "tests/backends/test_python_backend_support_services.py",
        "tests/backends/test_python_backend_federation_extended.py",
        "tests/backends/test_python_backend_object_ownership_extended.py",
        "tests/backends/test_python_backend_time_ddm_extended.py",
    ),
    "queryLookahead": ("tests/time/test_mom_mim_and_time_semantics_v010.py",),
    "retract": (
        "tests/time/test_mom_mim_time_v10.py",
        "tests/time/test_mom_mim_and_time_semantics_v010.py",
    ),
    "enableAsynchronousDelivery": (
        "tests/backends/test_python_backend_support_services.py",
        "tests/backends/test_python_backend_federation_extended.py",
        "tests/backends/test_python_backend_object_ownership_extended.py",
        "tests/backends/test_python_backend_time_ddm_extended.py",
    ),
    "disableAsynchronousDelivery": (
        "tests/backends/test_python_backend_support_services.py",
        "tests/backends/test_python_backend_federation_extended.py",
        "tests/backends/test_python_backend_object_ownership_extended.py",
        "tests/backends/test_python_backend_time_ddm_extended.py",
    ),
    "changeAttributeOrderType": (
        "tests/backends/test_python_backend_support_services.py",
        "tests/backends/test_python_backend_federation_extended.py",
        "tests/backends/test_python_backend_object_ownership_extended.py",
        "tests/backends/test_python_backend_time_ddm_extended.py",
    ),
    "changeInteractionOrderType": (
        "tests/backends/test_python_backend_support_services.py",
        "tests/backends/test_python_backend_federation_extended.py",
        "tests/backends/test_python_backend_object_ownership_extended.py",
        "tests/backends/test_python_backend_time_ddm_extended.py",
    ),
    "sendInteraction": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_exchange.py::run_two_federate_exchange_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_backend_exchange_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_exchange_matrix",
    ),
    "updateAttributeValues": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_exchange.py::run_two_federate_exchange_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_backend_exchange_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_exchange_matrix",
    ),
    "requestAttributeValueUpdate": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_request_attribute_value_update.py::run_request_attribute_value_update_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_request_attribute_value_update.py::run_request_attribute_value_update_routing_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_request_attribute_value_update_matrix",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_request_attribute_value_update_routing_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_request_attribute_value_update_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_request_attribute_value_update_routing_matrix",
    ),
    "discoverObjectInstance": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_exchange.py::run_two_federate_exchange_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_discovery_class.py::run_discovery_class_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_backend_exchange_matrix",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_discovery_class_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_exchange_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_discovery_class_matrix",
    ),
    "reflectAttributeValues": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_exchange.py::run_two_federate_exchange_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_request_attribute_value_update.py::run_request_attribute_value_update_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_backend_exchange_matrix",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_request_attribute_value_update_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_exchange_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_request_attribute_value_update_matrix",
    ),
    "receiveInteraction": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_exchange.py::run_two_federate_exchange_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_backend_exchange_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_exchange_matrix",
    ),
    "removeObjectInstance": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_exchange.py::run_two_federate_exchange_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_local_delete.py::run_local_delete_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_timed_delete.py::run_timed_delete_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_backend_exchange_matrix",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_local_delete_matrix",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_timed_delete_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_exchange_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_local_delete_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_timed_delete_matrix",
    ),
    "provideAttributeValueUpdate": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_request_attribute_value_update.py::run_request_attribute_value_update_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_request_attribute_value_update_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_request_attribute_value_update_matrix",
    ),
    "reportAttributeTransportationType": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_transportation_type.py::run_transportation_type_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_transportation_type_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_transportation_type_matrix",
    ),
    "reportInteractionTransportationType": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_transportation_type.py::run_transportation_type_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_transportation_type_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_transportation_type_matrix",
    ),
    "attributesInScope": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_object_scope.py::run_object_scope_relevance_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_object_scope_relevance_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_object_scope_relevance_matrix",
    ),
    "attributesOutOfScope": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_object_scope.py::run_object_scope_relevance_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_object_scope_relevance_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_object_scope_relevance_matrix",
    ),
    "turnUpdatesOnForObjectInstance": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_update_advisory.py::run_update_advisory_callback_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_update_advisory_callback_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_update_advisory_callback_matrix",
    ),
    "turnUpdatesOffForObjectInstance": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_update_advisory.py::run_update_advisory_callback_scenario",
        "tests/scenarios/test_object_management_backend_matrix.py::test_python_update_advisory_callback_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_update_advisory_callback_matrix",
    ),
    "unconditionalAttributeOwnershipDivestiture": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ownership.py::run_attribute_ownership_scenario",
        "tests/scenarios/test_ownership_management_backend_matrix.py::test_python_backend_ownership_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_ownership_matrix",
    ),
    "negotiatedAttributeOwnershipDivestiture": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ownership.py::run_negotiated_attribute_ownership_scenario",
        "tests/scenarios/test_ownership_management_backend_matrix.py::test_python_backend_negotiated_ownership_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_negotiated_ownership_matrix",
    ),
    "confirmDivestiture": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ownership.py::run_negotiated_attribute_ownership_scenario",
        "tests/scenarios/test_ownership_management_backend_matrix.py::test_python_backend_negotiated_ownership_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_negotiated_ownership_matrix",
    ),
    "attributeOwnershipAcquisition": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ownership.py::run_release_request_ownership_scenario",
        "tests/scenarios/test_ownership_management_backend_matrix.py::test_python_backend_release_request_ownership_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_release_request_owned_attribute_probe",
    ),
    "attributeOwnershipAcquisitionIfAvailable": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ownership.py::run_attribute_ownership_unavailable_scenario",
        "tests/scenarios/test_ownership_management_backend_matrix.py::test_python_backend_ownership_unavailable_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_ownership_unavailable_matrix",
    ),
    "attributeOwnershipReleaseDenied": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ownership.py::run_release_request_ownership_scenario",
        "tests/scenarios/test_ownership_management_backend_matrix.py::test_python_backend_release_denied_ownership_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_release_denied_ownership_matrix",
    ),
    "attributeOwnershipDivestitureIfWanted": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ownership.py::run_release_request_ownership_scenario",
        "tests/scenarios/test_ownership_management_backend_matrix.py::test_python_backend_release_request_ownership_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_release_request_owned_attribute_probe",
    ),
    "cancelAttributeOwnershipAcquisition": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ownership.py::run_negotiated_attribute_ownership_scenario",
        "tests/scenarios/test_ownership_management_backend_matrix.py::test_python_backend_negotiated_ownership_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_negotiated_ownership_matrix",
    ),
    "cancelNegotiatedAttributeOwnershipDivestiture": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ownership.py::run_negotiated_attribute_ownership_scenario",
        "tests/scenarios/test_ownership_management_backend_matrix.py::test_python_backend_negotiated_ownership_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_negotiated_ownership_matrix",
    ),
    "queryAttributeOwnership": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ownership.py::run_attribute_ownership_query_callback_scenario",
        "tests/scenarios/test_ownership_management_backend_matrix.py::test_python_attribute_ownership_query_callback_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_attribute_ownership_query_callback_matrix",
    ),
    "isAttributeOwnedByFederate": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ownership.py::run_attribute_ownership_query_callback_scenario",
        "tests/scenarios/test_ownership_management_backend_matrix.py::test_python_attribute_ownership_query_callback_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_attribute_ownership_query_callback_matrix",
    ),
    "requestAttributeOwnershipAssumption": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ownership.py::probe_negotiated_attribute_ownership_offer",
        "tests/scenarios/test_ownership_management_backend_matrix.py::test_python_negotiated_divesting_offer_probe_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_negotiated_divesting_offer_probe",
    ),
    "attributeOwnershipUnavailable": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ownership.py::run_attribute_ownership_unavailable_scenario",
        "tests/scenarios/test_ownership_management_backend_matrix.py::test_python_backend_ownership_unavailable_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_ownership_unavailable_matrix",
    ),
    "informAttributeOwnership": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ownership.py::run_attribute_ownership_query_callback_scenario",
        "tests/scenarios/test_ownership_management_backend_matrix.py::test_python_attribute_ownership_query_callback_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_attribute_ownership_query_callback_matrix",
    ),
    "attributeIsNotOwned": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ownership.py::run_attribute_ownership_query_callback_scenario",
        "tests/scenarios/test_ownership_management_backend_matrix.py::test_python_attribute_ownership_query_callback_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_attribute_ownership_query_callback_matrix",
    ),
    "attributeIsOwnedByRTI": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ownership.py::run_attribute_ownership_query_callback_scenario",
        "tests/scenarios/test_ownership_management_backend_matrix.py::test_python_attribute_ownership_query_callback_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_attribute_ownership_query_callback_matrix",
    ),
    "createRegion": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ddm_object_regions.py::run_ddm_object_region_lifecycle_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ddm_passive_regions.py::run_ddm_passive_region_subscription_scenario",
        "tests/scenarios/test_ddm_backend_matrix.py::test_python_backend_ddm_object_region_lifecycle_matrix",
        "tests/scenarios/test_ddm_backend_matrix.py::test_python_backend_ddm_passive_region_subscription_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_ddm_object_region_lifecycle_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_ddm_passive_region_subscription_matrix",
    ),
    "commitRegionModifications": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ddm_object_regions.py::run_ddm_object_region_lifecycle_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ddm_passive_regions.py::run_ddm_passive_region_subscription_scenario",
        "tests/scenarios/test_ddm_backend_matrix.py::test_python_backend_ddm_object_region_lifecycle_matrix",
        "tests/scenarios/test_ddm_backend_matrix.py::test_python_backend_ddm_passive_region_subscription_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_ddm_object_region_lifecycle_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_ddm_passive_region_subscription_matrix",
    ),
    "deleteRegion": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ddm_object_regions.py::run_ddm_object_region_lifecycle_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ddm_passive_regions.py::run_ddm_passive_region_subscription_scenario",
        "tests/scenarios/test_ddm_backend_matrix.py::test_python_backend_ddm_object_region_lifecycle_matrix",
        "tests/scenarios/test_ddm_backend_matrix.py::test_python_backend_ddm_passive_region_subscription_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_ddm_object_region_lifecycle_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_ddm_passive_region_subscription_matrix",
    ),
    "registerObjectInstanceWithRegions": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ddm_object_regions.py::run_ddm_object_region_lifecycle_scenario",
        "tests/scenarios/test_ddm_backend_matrix.py::test_python_backend_ddm_object_region_lifecycle_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_ddm_object_region_lifecycle_matrix",
    ),
    "associateRegionsForUpdates": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ddm_object_regions.py::run_ddm_object_region_lifecycle_scenario",
        "tests/scenarios/test_ddm_backend_matrix.py::test_python_backend_ddm_object_region_lifecycle_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_ddm_object_region_lifecycle_matrix",
    ),
    "unassociateRegionsForUpdates": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ddm_object_regions.py::run_ddm_object_region_lifecycle_scenario",
        "tests/scenarios/test_ddm_backend_matrix.py::test_python_backend_ddm_object_region_lifecycle_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_ddm_object_region_lifecycle_matrix",
    ),
    "subscribeObjectClassAttributesWithRegions": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ddm_object_regions.py::run_ddm_object_region_lifecycle_scenario",
        "tests/scenarios/test_ddm_backend_matrix.py::test_python_backend_ddm_object_region_lifecycle_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_ddm_object_region_lifecycle_matrix",
    ),
    "subscribeObjectClassAttributesPassivelyWithRegions": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ddm_passive_regions.py::run_ddm_passive_region_subscription_scenario",
        "tests/scenarios/test_ddm_backend_matrix.py::test_python_backend_ddm_passive_region_subscription_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_ddm_passive_region_subscription_matrix",
    ),
    "unsubscribeObjectClassAttributesWithRegions": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ddm_object_regions.py::run_ddm_object_region_lifecycle_scenario",
        "tests/scenarios/test_ddm_backend_matrix.py::test_python_backend_ddm_object_region_lifecycle_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_ddm_object_region_lifecycle_matrix",
    ),
    "subscribeInteractionClassWithRegions": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ddm_object_regions.py::run_ddm_object_region_lifecycle_scenario",
        "tests/scenarios/test_ddm_backend_matrix.py::test_python_backend_ddm_object_region_lifecycle_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_ddm_object_region_lifecycle_matrix",
    ),
    "subscribeInteractionClassPassivelyWithRegions": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ddm_passive_regions.py::run_ddm_passive_region_subscription_scenario",
        "tests/scenarios/test_ddm_backend_matrix.py::test_python_backend_ddm_passive_region_subscription_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_ddm_passive_region_subscription_matrix",
    ),
    "unsubscribeInteractionClassWithRegions": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ddm_object_regions.py::run_ddm_object_region_lifecycle_scenario",
        "tests/scenarios/test_ddm_backend_matrix.py::test_python_backend_ddm_object_region_lifecycle_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_ddm_object_region_lifecycle_matrix",
    ),
    "sendInteractionWithRegions": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/two_federate_suite_scenarios.py::run_suite_ddm_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ddm_object_regions.py::run_ddm_object_region_lifecycle_scenario",
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ddm_passive_regions.py::run_ddm_passive_region_subscription_scenario",
        "tests/scenarios/test_ddm_backend_matrix.py::test_python_backend_ddm_matrix",
        "tests/scenarios/test_ddm_backend_matrix.py::test_python_backend_ddm_object_region_lifecycle_matrix",
        "tests/scenarios/test_ddm_backend_matrix.py::test_python_backend_ddm_passive_region_subscription_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_ddm_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_ddm_object_region_lifecycle_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_ddm_passive_region_subscription_matrix",
    ),
    "requestAttributeValueUpdateWithRegions": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_ddm_object_regions.py::run_ddm_object_region_lifecycle_scenario",
        "tests/scenarios/test_ddm_backend_matrix.py::test_python_backend_ddm_object_region_lifecycle_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_ddm_object_region_lifecycle_matrix",
    ),
    "getFederateName": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getFederateHandle": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getObjectClassHandle": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getObjectClassName": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getAttributeHandle": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getAttributeName": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getInteractionClassHandle": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getInteractionClassName": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getParameterHandle": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getParameterName": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getObjectInstanceHandle": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getObjectInstanceName": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getKnownObjectClassHandle": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getDimensionHandle": (
        "tests/factories/test_fom_time_factories.py",
        "tests/verification/test_spec_traceability_and_extended_python_rti.py",
        "tests/backends/test_python_backend_support_services.py",
        "tests/backends/test_python_backend_federation_extended.py",
        "tests/backends/test_python_backend_object_ownership_extended.py",
        "tests/backends/test_python_backend_time_ddm_extended.py",
    ),
    "getDimensionName": (
        "tests/backends/test_python_backend_support_services.py",
        "tests/backends/test_python_backend_federation_extended.py",
        "tests/backends/test_python_backend_object_ownership_extended.py",
        "tests/backends/test_python_backend_time_ddm_extended.py",
    ),
    "getTransportationTypeHandle": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getTransportationTypeName": ("tests/verification/test_spec_traceability_and_extended_python_rti.py",),
    "getHLAversion": (
        "tests/transport/test_grpc_transport.py",
        "tests/transport/test_rest_transport.py",
        "tests/backends/test_certi_backend_transport.py",
    ),
    "getDimensionHandleSet": (
        "tests/factories/test_fom_time_factories.py",
        "tests/backends/test_python_backend_support_services.py",
        "tests/backends/test_python_backend_federation_extended.py",
        "tests/backends/test_python_backend_object_ownership_extended.py",
        "tests/backends/test_python_backend_time_ddm_extended.py",
    ),
    "getOrderName": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getOrderType": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getTransportationType": ("tests/verification/test_spec_traceability_and_extended_python_rti.py",),
    "getTransportationName": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getAvailableDimensionsForClassAttribute": (
        "tests/verification/test_spec_traceability_and_extended_python_rti.py",
        "tests/backends/test_python_backend_support_services.py",
        "tests/backends/test_python_backend_federation_extended.py",
        "tests/backends/test_python_backend_object_ownership_extended.py",
        "tests/backends/test_python_backend_time_ddm_extended.py",
    ),
    "getAvailableDimensionsForInteractionClass": ("tests/verification/test_spec_traceability_and_extended_python_rti.py",),
    "getUpdateRateValue": ("tests/verification/test_spec_traceability_and_extended_python_rti.py",),
    "getUpdateRateValueForAttribute": ("tests/verification/test_spec_traceability_and_extended_python_rti.py",),
    "normalizeFederateHandle": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "normalizeServiceGroup": ("tests/verification/test_spec_traceability_and_extended_python_rti.py",),
    "getAttributeSetRegionSetPairListFactory": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getAutomaticResignDirective": ("tests/verification/test_spec_traceability_and_extended_python_rti.py",),
    "setAutomaticResignDirective": ("tests/verification/test_spec_traceability_and_extended_python_rti.py",),
    "enableObjectClassRelevanceAdvisorySwitch": ("tests/verification/test_spec_traceability_and_extended_python_rti.py",),
    "disableObjectClassRelevanceAdvisorySwitch": ("tests/verification/test_spec_traceability_and_extended_python_rti.py",),
    "enableAttributeRelevanceAdvisorySwitch": ("tests/verification/test_spec_traceability_and_extended_python_rti.py",),
    "disableAttributeRelevanceAdvisorySwitch": ("tests/verification/test_spec_traceability_and_extended_python_rti.py",),
    "enableAttributeScopeAdvisorySwitch": ("tests/verification/test_spec_traceability_and_extended_python_rti.py",),
    "disableAttributeScopeAdvisorySwitch": ("tests/verification/test_spec_traceability_and_extended_python_rti.py",),
    "enableInteractionRelevanceAdvisorySwitch": ("tests/verification/test_spec_traceability_and_extended_python_rti.py",),
    "disableInteractionRelevanceAdvisorySwitch": ("tests/verification/test_spec_traceability_and_extended_python_rti.py",),
    "enableCallbacks": (
        "tests/backends/test_python_backend_support_services.py",
        "tests/backends/test_python_backend_federation_extended.py",
        "tests/backends/test_python_backend_object_ownership_extended.py",
        "tests/backends/test_python_backend_time_ddm_extended.py",
    ),
    "disableCallbacks": (
        "tests/backends/test_python_backend_support_services.py",
        "tests/backends/test_python_backend_federation_extended.py",
        "tests/backends/test_python_backend_object_ownership_extended.py",
        "tests/backends/test_python_backend_time_ddm_extended.py",
    ),
    "evokeCallback": (
        "tests/transport/test_rest_transport.py",
        "tests/transport/test_grpc_transport_python_server.py",
        "tests/backends/test_python_backend_support_services.py",
        "tests/backends/test_python_backend_federation_extended.py",
        "tests/backends/test_python_backend_object_ownership_extended.py",
        "tests/backends/test_python_backend_time_ddm_extended.py",
    ),
    "evokeMultipleCallbacks": (
        "tests/transport/test_rest_transport.py",
        "tests/transport/test_grpc_transport_python_server.py",
        "tests/backends/test_python_backend_support_services.py",
        "tests/backends/test_python_backend_federation_extended.py",
        "tests/backends/test_python_backend_object_ownership_extended.py",
        "tests/backends/test_python_backend_time_ddm_extended.py",
    ),
    "getRangeBounds": (
        "tests/verification/test_spec_traceability_and_extended_python_rti.py",
        "tests/backends/test_python_backend_support_services.py",
        "tests/backends/test_python_backend_federation_extended.py",
        "tests/backends/test_python_backend_object_ownership_extended.py",
        "tests/backends/test_python_backend_time_ddm_extended.py",
    ),
    "setRangeBounds": (
        "tests/verification/test_spec_traceability_and_extended_python_rti.py",
        "tests/backends/test_python_backend_support_services.py",
        "tests/backends/test_python_backend_federation_extended.py",
        "tests/backends/test_python_backend_object_ownership_extended.py",
        "tests/backends/test_python_backend_time_ddm_extended.py",
    ),
    "getDimensionUpperBound": (
        "tests/verification/test_spec_traceability_and_extended_python_rti.py",
        "tests/backends/test_python_backend_support_services.py",
        "tests/backends/test_python_backend_federation_extended.py",
        "tests/backends/test_python_backend_object_ownership_extended.py",
        "tests/backends/test_python_backend_time_ddm_extended.py",
    ),
    "getTimeFactory": ("tests/factories/test_fom_time_factories.py",),
    "getAttributeHandleFactory": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getAttributeHandleSetFactory": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getAttributeHandleValueMapFactory": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getDimensionHandleFactory": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getDimensionHandleSetFactory": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getFederateHandleFactory": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getFederateHandleSetFactory": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getInteractionClassHandleFactory": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getObjectClassHandleFactory": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getObjectInstanceHandleFactory": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getParameterHandleFactory": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getParameterHandleValueMapFactory": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getRegionHandleSetFactory": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "getTransportationTypeHandleFactory": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "decodeAttributeHandle": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "decodeDimensionHandle": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "decodeFederateHandle": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "decodeInteractionClassHandle": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "decodeMessageRetractionHandle": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "decodeObjectClassHandle": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "decodeObjectInstanceHandle": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "decodeParameterHandle": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
    "decodeRegionHandle": (
        "packages/hla2010-verification-harness/src/hla2010_verification_harness/scenario_support_services.py::run_support_factory_and_decode_scenario",
        "tests/scenarios/test_support_services_backend_matrix.py::test_python_backend_support_factory_and_decode_matrix",
        "tests/vendors/test_pitch_real_backend_matrix.py::test_pitch_backend_support_factory_and_decode_matrix",
    ),
}



def focused_evidence_by_method() -> dict[str, tuple[str, ...]]:
    return _FOCUSED_EVIDENCE_BY_METHOD


__all__ = ["focused_evidence_by_method"]
