"""Encoding protocols for IEEE 1516.1-2025.

Sources: Java hla/rti1516_2025/encoding/*.java, C++ RTI/encoding/*.h, and HLAstandardMIM-2025 XML for HLAtransportationTypeHandle.
"""

from __future__ import annotations
# pyright: reportInvalidTypeVarUse=false

from typing import Generic, Iterable, Iterator, Protocol, Sequence, TypeVar, overload, runtime_checkable

from ._byte_wrapper import ByteWrapper
from .handles import (
    AttributeHandle,
    DimensionHandle,
    FederateHandle,
    InteractionClassHandle,
    MessageRetractionHandle,
    ObjectClassHandle,
    ObjectInstanceHandle,
    ParameterHandle,
    RegionHandle,
    TransportationTypeHandle,
)
from .logical_time import LogicalTime, LogicalTimeInterval

BytesLike = bytes | bytearray | memoryview
T = TypeVar("T")
D = TypeVar("D", bound="DataElement")
LT = TypeVar("LT", bound=LogicalTime)
LTI = TypeVar("LTI", bound=LogicalTimeInterval)


class EncoderException(Exception):
    pass


class DecoderException(Exception):
    pass


@runtime_checkable
class VariableLengthData(Protocol):
    """C++ VariableLengthData equivalent for encoded byte sequences."""

    def data(self) -> bytes: ...

    def size(self) -> int: ...

    def setData(self, data: BytesLike) -> None: ...


@runtime_checkable
class DataElement(Protocol):
    def getOctetBoundary(self) -> int: ...

    @overload
    def encode(self) -> ByteWrapper | VariableLengthData: ...

    @overload
    def encode(self, byteWrapper: ByteWrapper) -> None: ...

    @overload
    def encode(self, inData: VariableLengthData) -> None: ...

    def encode(
        self, target: ByteWrapper | VariableLengthData | None = None
    ) -> ByteWrapper | VariableLengthData | None: ...

    def encodeInto(self, buffer: bytearray) -> None: ...

    def getEncodedLength(self) -> int: ...

    def toByteArray(self) -> bytes: ...

    @overload
    def decode(self: D, byteWrapper: ByteWrapper) -> D: ...

    @overload
    def decode(self: D, data: BytesLike | VariableLengthData) -> D: ...

    def decode(self: D, source: ByteWrapper | BytesLike | VariableLengthData) -> D: ...

    def clone(self: D) -> D: ...

    def isSameTypeAs(self, inData: DataElement) -> bool: ...

    def hash(self) -> int: ...


@runtime_checkable
class DataElementFactory(Protocol[D]):
    def createElement(self, index: int = 0) -> D: ...


@runtime_checkable
class ValueDataElement(DataElement, Protocol[T]):
    def getValue(self) -> T: ...

    def setValue(self: D, value: T) -> D: ...


class HLAASCIIchar(ValueDataElement[int], Protocol): ...
class HLAASCIIstring(ValueDataElement[str], Protocol): ...
class HLAboolean(ValueDataElement[bool], Protocol): ...
class HLAbyte(ValueDataElement[int], Protocol): ...
class HLAfloat32BE(ValueDataElement[float], Protocol): ...
class HLAfloat32LE(ValueDataElement[float], Protocol): ...
class HLAfloat64BE(ValueDataElement[float], Protocol): ...
class HLAfloat64LE(ValueDataElement[float], Protocol): ...
class HLAinteger16BE(ValueDataElement[int], Protocol): ...
class HLAinteger16LE(ValueDataElement[int], Protocol): ...
class HLAinteger32BE(ValueDataElement[int], Protocol): ...
class HLAinteger32LE(ValueDataElement[int], Protocol): ...
class HLAinteger64BE(ValueDataElement[int], Protocol): ...
class HLAinteger64LE(ValueDataElement[int], Protocol): ...
class HLAunsignedInteger16BE(ValueDataElement[int], Protocol): ...
class HLAunsignedInteger16LE(ValueDataElement[int], Protocol): ...
class HLAunsignedInteger32BE(ValueDataElement[int], Protocol): ...
class HLAunsignedInteger32LE(ValueDataElement[int], Protocol): ...
class HLAunsignedInteger64BE(ValueDataElement[int], Protocol): ...
class HLAunsignedInteger64LE(ValueDataElement[int], Protocol): ...
class HLAoctet(ValueDataElement[int], Protocol): ...
class HLAoctetPairBE(ValueDataElement[int], Protocol): ...
class HLAoctetPairLE(ValueDataElement[int], Protocol): ...
class HLAunicodeChar(ValueDataElement[int], Protocol): ...
class HLAunicodeString(ValueDataElement[str], Protocol): ...


class HLAopaqueData(ValueDataElement[bytes], Iterable[int], Protocol):
    def size(self) -> int: ...
    def get(self, index: int) -> int: ...
    def __iter__(self) -> Iterator[int]: ...
    def setValue(self: D, value: BytesLike | Sequence[int]) -> D: ...


class HLAfixedArray(DataElement, Iterable[D], Protocol[D]):
    def size(self) -> int: ...
    def get(self, index: int) -> D: ...
    def __iter__(self) -> Iterator[D]: ...
    def set(self, index: int, dataElement: D) -> HLAfixedArray[D]: ...


class HLAvariableArray(DataElement, Iterable[D], Protocol[D]):
    def addElement(self, dataElement: D) -> HLAvariableArray[D]: ...
    def size(self) -> int: ...
    def get(self, index: int) -> D: ...
    def __iter__(self) -> Iterator[D]: ...
    def resize(self, newSize: int) -> HLAvariableArray[D]: ...
    def set(self, index: int, dataElement: D) -> HLAvariableArray[D]: ...


class HLAfixedRecord(DataElement, Iterable[DataElement], Protocol):
    def add(self, dataElement: DataElement) -> None: ...
    def appendElement(self, dataElement: DataElement) -> HLAfixedRecord: ...
    def size(self) -> int: ...
    def get(self, index: int) -> DataElement: ...
    def __iter__(self) -> Iterator[DataElement]: ...
    def set(self, index: int, dataElement: DataElement) -> HLAfixedRecord: ...


class HLAvariantRecord(DataElement, Protocol[D]):
    def setVariant(self, discriminant: D, dataElement: DataElement) -> HLAvariantRecord[D]: ...
    def setDiscriminant(self, discriminant: D) -> HLAvariantRecord[D]: ...
    def getDiscriminant(self) -> D: ...
    def getValue(self) -> DataElement: ...


class HLAextendableVariantRecord(HLAvariantRecord[D], Protocol[D]): ...


class HLAfederateHandle(ValueDataElement[FederateHandle], Protocol): ...
class HLAobjectClassHandle(ValueDataElement[ObjectClassHandle], Protocol): ...
class HLAinteractionClassHandle(ValueDataElement[InteractionClassHandle], Protocol): ...
class HLAobjectInstanceHandle(ValueDataElement[ObjectInstanceHandle], Protocol): ...
class HLAattributeHandle(ValueDataElement[AttributeHandle], Protocol): ...
class HLAparameterHandle(ValueDataElement[ParameterHandle], Protocol): ...
class HLAdimensionHandle(ValueDataElement[DimensionHandle], Protocol): ...
class HLAmessageRetractionHandle(ValueDataElement[MessageRetractionHandle], Protocol): ...
class HLAregionHandle(ValueDataElement[RegionHandle], Protocol): ...
class HLAtransportationTypeHandle(ValueDataElement[TransportationTypeHandle], Protocol): ...


class HLAlogicalTime(ValueDataElement[LT], Protocol[LT, LTI]): ...
class HLAlogicalTimeInterval(ValueDataElement[LTI], Protocol[LT, LTI]): ...


@runtime_checkable
class EncoderFactory(Protocol):
    # Primitive HLA data types. Optional value arguments collapse the Java
    # overloaded factory methods into typed Python signatures.
    # Source: Java encoding/EncoderFactory.java declares createHLAASCIIchar() and createHLAASCIIchar(value).
    @overload
    def createHLAASCIIchar(self) -> HLAASCIIchar: ...

    @overload
    def createHLAASCIIchar(self, value: int) -> HLAASCIIchar: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAASCIIstring() and createHLAASCIIstring(value).
    @overload
    def createHLAASCIIstring(self) -> HLAASCIIstring: ...

    @overload
    def createHLAASCIIstring(self, value: str) -> HLAASCIIstring: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAboolean() and createHLAboolean(value).
    @overload
    def createHLAboolean(self) -> HLAboolean: ...

    @overload
    def createHLAboolean(self, value: bool) -> HLAboolean: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAbyte() and createHLAbyte(value).
    @overload
    def createHLAbyte(self) -> HLAbyte: ...

    @overload
    def createHLAbyte(self, value: int) -> HLAbyte: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAfloat32BE() and createHLAfloat32BE(value).
    @overload
    def createHLAfloat32BE(self) -> HLAfloat32BE: ...

    @overload
    def createHLAfloat32BE(self, value: float) -> HLAfloat32BE: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAfloat32LE() and createHLAfloat32LE(value).
    @overload
    def createHLAfloat32LE(self) -> HLAfloat32LE: ...

    @overload
    def createHLAfloat32LE(self, value: float) -> HLAfloat32LE: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAfloat64BE() and createHLAfloat64BE(value).
    @overload
    def createHLAfloat64BE(self) -> HLAfloat64BE: ...

    @overload
    def createHLAfloat64BE(self, value: float) -> HLAfloat64BE: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAfloat64LE() and createHLAfloat64LE(value).
    @overload
    def createHLAfloat64LE(self) -> HLAfloat64LE: ...

    @overload
    def createHLAfloat64LE(self, value: float) -> HLAfloat64LE: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAinteger16BE() and createHLAinteger16BE(value).
    @overload
    def createHLAinteger16BE(self) -> HLAinteger16BE: ...

    @overload
    def createHLAinteger16BE(self, value: int) -> HLAinteger16BE: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAinteger16LE() and createHLAinteger16LE(value).
    @overload
    def createHLAinteger16LE(self) -> HLAinteger16LE: ...

    @overload
    def createHLAinteger16LE(self, value: int) -> HLAinteger16LE: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAinteger32BE() and createHLAinteger32BE(value).
    @overload
    def createHLAinteger32BE(self) -> HLAinteger32BE: ...

    @overload
    def createHLAinteger32BE(self, value: int) -> HLAinteger32BE: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAinteger32LE() and createHLAinteger32LE(value).
    @overload
    def createHLAinteger32LE(self) -> HLAinteger32LE: ...

    @overload
    def createHLAinteger32LE(self, value: int) -> HLAinteger32LE: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAinteger64BE() and createHLAinteger64BE(value).
    @overload
    def createHLAinteger64BE(self) -> HLAinteger64BE: ...

    @overload
    def createHLAinteger64BE(self, value: int) -> HLAinteger64BE: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAinteger64LE() and createHLAinteger64LE(value).
    @overload
    def createHLAinteger64LE(self) -> HLAinteger64LE: ...

    @overload
    def createHLAinteger64LE(self, value: int) -> HLAinteger64LE: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAunsignedInteger16BE() and createHLAunsignedInteger16BE(value).
    @overload
    def createHLAunsignedInteger16BE(self) -> HLAunsignedInteger16BE: ...

    @overload
    def createHLAunsignedInteger16BE(self, value: int) -> HLAunsignedInteger16BE: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAunsignedInteger16LE() and createHLAunsignedInteger16LE(value).
    @overload
    def createHLAunsignedInteger16LE(self) -> HLAunsignedInteger16LE: ...

    @overload
    def createHLAunsignedInteger16LE(self, value: int) -> HLAunsignedInteger16LE: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAunsignedInteger32BE() and createHLAunsignedInteger32BE(value).
    @overload
    def createHLAunsignedInteger32BE(self) -> HLAunsignedInteger32BE: ...

    @overload
    def createHLAunsignedInteger32BE(self, value: int) -> HLAunsignedInteger32BE: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAunsignedInteger32LE() and createHLAunsignedInteger32LE(value).
    @overload
    def createHLAunsignedInteger32LE(self) -> HLAunsignedInteger32LE: ...

    @overload
    def createHLAunsignedInteger32LE(self, value: int) -> HLAunsignedInteger32LE: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAunsignedInteger64BE() and createHLAunsignedInteger64BE(value).
    @overload
    def createHLAunsignedInteger64BE(self) -> HLAunsignedInteger64BE: ...

    @overload
    def createHLAunsignedInteger64BE(self, value: int) -> HLAunsignedInteger64BE: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAunsignedInteger64LE() and createHLAunsignedInteger64LE(value).
    @overload
    def createHLAunsignedInteger64LE(self) -> HLAunsignedInteger64LE: ...

    @overload
    def createHLAunsignedInteger64LE(self, value: int) -> HLAunsignedInteger64LE: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAoctet() and createHLAoctet(value).
    @overload
    def createHLAoctet(self) -> HLAoctet: ...

    @overload
    def createHLAoctet(self, value: int) -> HLAoctet: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAoctetPairBE() and createHLAoctetPairBE(value).
    @overload
    def createHLAoctetPairBE(self) -> HLAoctetPairBE: ...

    @overload
    def createHLAoctetPairBE(self, value: int) -> HLAoctetPairBE: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAoctetPairLE() and createHLAoctetPairLE(value).
    @overload
    def createHLAoctetPairLE(self) -> HLAoctetPairLE: ...

    @overload
    def createHLAoctetPairLE(self, value: int) -> HLAoctetPairLE: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAopaqueData() and createHLAopaqueData(value).
    @overload
    def createHLAopaqueData(self) -> HLAopaqueData: ...

    @overload
    def createHLAopaqueData(self, value: BytesLike) -> HLAopaqueData: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAunicodeChar() and createHLAunicodeChar(value).
    @overload
    def createHLAunicodeChar(self) -> HLAunicodeChar: ...

    @overload
    def createHLAunicodeChar(self, value: int) -> HLAunicodeChar: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAunicodeString() and createHLAunicodeString(value).
    @overload
    def createHLAunicodeString(self) -> HLAunicodeString: ...

    @overload
    def createHLAunicodeString(self, value: str) -> HLAunicodeString: ...

    # Complex HLA data types.
    @overload
    def createHLAfixedArray(self, factory: DataElementFactory[D], size: int) -> HLAfixedArray[D]: ...

    @overload
    def createHLAfixedArray(self, *elements: D) -> HLAfixedArray[D]: ...

    def createHLAfixedArray(
        self,
        factoryOrFirstElement: DataElementFactory[D] | D,
        sizeOrSecondElement: int | D | None = None,
        *elements: D,
    ) -> HLAfixedArray[D]: ...

    def createHLAvariableArray(self, factory: DataElementFactory[D], *elements: D) -> HLAvariableArray[D]: ...
    def createHLAfixedRecord(self) -> HLAfixedRecord: ...
    def createHLAvariantRecord(self, discriminant: D) -> HLAvariantRecord[D]: ...
    def createHLAextendableVariantRecord(self, discriminant: D) -> HLAextendableVariantRecord[D]: ...

    # Encoded RTI handles and time values.
    # Source: Java encoding/EncoderFactory.java declares createHLAfederateHandle(RTIambassador) and createHLAfederateHandle(RTIambassador, handle).
    @overload
    def createHLAfederateHandle(self, rtiAmbassador) -> HLAfederateHandle: ...

    @overload
    def createHLAfederateHandle(self, rtiAmbassador, federateHandle: FederateHandle) -> HLAfederateHandle: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAobjectClassHandle(RTIambassador) and createHLAobjectClassHandle(RTIambassador, handle).
    @overload
    def createHLAobjectClassHandle(self, rtiAmbassador) -> HLAobjectClassHandle: ...

    @overload
    def createHLAobjectClassHandle(self, rtiAmbassador, objectClassHandle: ObjectClassHandle) -> HLAobjectClassHandle: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAinteractionClassHandle(RTIambassador) and createHLAinteractionClassHandle(RTIambassador, handle).
    @overload
    def createHLAinteractionClassHandle(self, rtiAmbassador) -> HLAinteractionClassHandle: ...

    @overload
    def createHLAinteractionClassHandle(self, rtiAmbassador, interactionClassHandle: InteractionClassHandle) -> HLAinteractionClassHandle: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAobjectInstanceHandle(RTIambassador) and createHLAobjectInstanceHandle(RTIambassador, handle).
    @overload
    def createHLAobjectInstanceHandle(self, rtiAmbassador) -> HLAobjectInstanceHandle: ...

    @overload
    def createHLAobjectInstanceHandle(self, rtiAmbassador, objectInstanceHandle: ObjectInstanceHandle) -> HLAobjectInstanceHandle: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAattributeHandle(RTIambassador) and createHLAattributeHandle(RTIambassador, handle).
    @overload
    def createHLAattributeHandle(self, rtiAmbassador) -> HLAattributeHandle: ...

    @overload
    def createHLAattributeHandle(self, rtiAmbassador, attributeHandle: AttributeHandle) -> HLAattributeHandle: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAparameterHandle(RTIambassador) and createHLAparameterHandle(RTIambassador, handle).
    @overload
    def createHLAparameterHandle(self, rtiAmbassador) -> HLAparameterHandle: ...

    @overload
    def createHLAparameterHandle(self, rtiAmbassador, parameterHandle: ParameterHandle) -> HLAparameterHandle: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAdimensionHandle(RTIambassador) and createHLAdimensionHandle(RTIambassador, handle).
    @overload
    def createHLAdimensionHandle(self, rtiAmbassador) -> HLAdimensionHandle: ...

    @overload
    def createHLAdimensionHandle(self, rtiAmbassador, dimensionHandle: DimensionHandle) -> HLAdimensionHandle: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAmessageRetractionHandle(RTIambassador) and createHLAmessageRetractionHandle(RTIambassador, handle).
    @overload
    def createHLAmessageRetractionHandle(self, rtiAmbassador) -> HLAmessageRetractionHandle: ...

    @overload
    def createHLAmessageRetractionHandle(self, rtiAmbassador, messageRetractionHandle: MessageRetractionHandle) -> HLAmessageRetractionHandle: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAregionHandle(RTIambassador) and createHLAregionHandle(RTIambassador, handle).
    @overload
    def createHLAregionHandle(self, rtiAmbassador) -> HLAregionHandle: ...

    @overload
    def createHLAregionHandle(self, rtiAmbassador, regionHandle: RegionHandle) -> HLAregionHandle: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAtransportationTypeHandle(RTIambassador) and createHLAtransportationTypeHandle(RTIambassador, handle).
    @overload
    def createHLAtransportationTypeHandle(self, rtiAmbassador) -> HLAtransportationTypeHandle: ...

    @overload
    def createHLAtransportationTypeHandle(self, rtiAmbassador, transportationTypeHandle: TransportationTypeHandle) -> HLAtransportationTypeHandle: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAlogicalTime(RTIambassador) and createHLAlogicalTime(RTIambassador, LogicalTime).
    @overload
    def createHLAlogicalTime(self, rtiAmbassador) -> HLAlogicalTime[LT, LTI]: ...

    @overload
    def createHLAlogicalTime(self, rtiAmbassador, logicalTime: LT) -> HLAlogicalTime[LT, LTI]: ...
    # Source: Java encoding/EncoderFactory.java declares createHLAlogicalTimeInterval(RTIambassador) and createHLAlogicalTimeInterval(RTIambassador, LogicalTimeInterval).
    @overload
    def createHLAlogicalTimeInterval(self, rtiAmbassador) -> HLAlogicalTimeInterval[LT, LTI]: ...

    @overload
    def createHLAlogicalTimeInterval(self, rtiAmbassador, logicalTimeInterval: LTI) -> HLAlogicalTimeInterval[LT, LTI]: ...
