# Generated from specs/hla2010_api.json and analysis/compliance/requirements_ledger.csv.
# Do not edit by hand. Run python3 scripts/generate_python_rti_service_map.py generate.
"""Stable Python RTI service registry.

Maps each HLA RTI method name to the concrete `_svc_*` implementation symbol
resolved from `PythonRTIBackend`.
"""
from __future__ import annotations

PYTHON_RTI_SERVICE_REGISTRY: dict[str, str] = {
  "abortFederationRestore": "hla2010_rti_python.save_restore_services.PythonRTISaveRestoreServicesMixin._svc_abortFederationRestore",
  "abortFederationSave": "hla2010_rti_python.save_restore_services.PythonRTISaveRestoreServicesMixin._svc_abortFederationSave",
  "associateRegionsForUpdates": "hla2010_rti_python.ddm_services.PythonRTIDdmServicesMixin._svc_associateRegionsForUpdates",
  "attributeOwnershipAcquisition": "hla2010_rti_python.ownership_services.PythonRTIOwnershipServicesMixin._svc_attributeOwnershipAcquisition",
  "attributeOwnershipAcquisitionIfAvailable": "hla2010_rti_python.ownership_services.PythonRTIOwnershipServicesMixin._svc_attributeOwnershipAcquisitionIfAvailable",
  "attributeOwnershipDivestitureIfWanted": "hla2010_rti_python.ownership_services.PythonRTIOwnershipServicesMixin._svc_attributeOwnershipDivestitureIfWanted",
  "attributeOwnershipReleaseDenied": "hla2010_rti_python.ownership_services.PythonRTIOwnershipServicesMixin._svc_attributeOwnershipReleaseDenied",
  "cancelAttributeOwnershipAcquisition": "hla2010_rti_python.ownership_services.PythonRTIOwnershipServicesMixin._svc_cancelAttributeOwnershipAcquisition",
  "cancelNegotiatedAttributeOwnershipDivestiture": "hla2010_rti_python.ownership_services.PythonRTIOwnershipServicesMixin._svc_cancelNegotiatedAttributeOwnershipDivestiture",
  "changeAttributeOrderType": "hla2010_rti_python.time_public_services.PythonRTITimePublicServicesMixin._svc_changeAttributeOrderType",
  "changeInteractionOrderType": "hla2010_rti_python.time_public_services.PythonRTITimePublicServicesMixin._svc_changeInteractionOrderType",
  "commitRegionModifications": "hla2010_rti_python.ddm_services.PythonRTIDdmServicesMixin._svc_commitRegionModifications",
  "confirmDivestiture": "hla2010_rti_python.ownership_services.PythonRTIOwnershipServicesMixin._svc_confirmDivestiture",
  "connect": "hla2010_rti_python.federation_creation.PythonRTIFederationCreationMixin._svc_connect",
  "createFederationExecution": "hla2010_rti_python.federation_creation.PythonRTIFederationCreationMixin._svc_createFederationExecution",
  "createFederationExecutionWithMIM": "hla2010_rti_python.federation_creation.PythonRTIFederationCreationMixin._svc_createFederationExecutionWithMIM",
  "createRegion": "hla2010_rti_python.ddm_services.PythonRTIDdmServicesMixin._svc_createRegion",
  "decodeAttributeHandle": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_decodeAttributeHandle",
  "decodeDimensionHandle": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_decodeDimensionHandle",
  "decodeFederateHandle": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_decodeFederateHandle",
  "decodeInteractionClassHandle": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_decodeInteractionClassHandle",
  "decodeMessageRetractionHandle": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_decodeMessageRetractionHandle",
  "decodeObjectClassHandle": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_decodeObjectClassHandle",
  "decodeObjectInstanceHandle": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_decodeObjectInstanceHandle",
  "decodeParameterHandle": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_decodeParameterHandle",
  "decodeRegionHandle": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_decodeRegionHandle",
  "deleteObjectInstance": "hla2010_rti_python.object_delivery_control.PythonRTIObjectDeliveryControlMixin._svc_deleteObjectInstance",
  "deleteRegion": "hla2010_rti_python.ddm_services.PythonRTIDdmServicesMixin._svc_deleteRegion",
  "destroyFederationExecution": "hla2010_rti_python.federation_creation.PythonRTIFederationCreationMixin._svc_destroyFederationExecution",
  "disableAsynchronousDelivery": "hla2010_rti_python.callbacks.PythonRTICallbacksMixin._svc_disableAsynchronousDelivery",
  "disableAttributeRelevanceAdvisorySwitch": "hla2010_rti_python.support_control.PythonRTISupportControlMixin._svc_disableAttributeRelevanceAdvisorySwitch",
  "disableAttributeScopeAdvisorySwitch": "hla2010_rti_python.support_control.PythonRTISupportControlMixin._svc_disableAttributeScopeAdvisorySwitch",
  "disableCallbacks": "hla2010_rti_python.callbacks.PythonRTICallbacksMixin._svc_disableCallbacks",
  "disableInteractionRelevanceAdvisorySwitch": "hla2010_rti_python.support_control.PythonRTISupportControlMixin._svc_disableInteractionRelevanceAdvisorySwitch",
  "disableObjectClassRelevanceAdvisorySwitch": "hla2010_rti_python.support_control.PythonRTISupportControlMixin._svc_disableObjectClassRelevanceAdvisorySwitch",
  "disableTimeConstrained": "hla2010_rti_python.time_public_services.PythonRTITimePublicServicesMixin._svc_disableTimeConstrained",
  "disableTimeRegulation": "hla2010_rti_python.time_public_services.PythonRTITimePublicServicesMixin._svc_disableTimeRegulation",
  "disconnect": "hla2010_rti_python.federation_creation.PythonRTIFederationCreationMixin._svc_disconnect",
  "enableAsynchronousDelivery": "hla2010_rti_python.callbacks.PythonRTICallbacksMixin._svc_enableAsynchronousDelivery",
  "enableAttributeRelevanceAdvisorySwitch": "hla2010_rti_python.support_control.PythonRTISupportControlMixin._svc_enableAttributeRelevanceAdvisorySwitch",
  "enableAttributeScopeAdvisorySwitch": "hla2010_rti_python.support_control.PythonRTISupportControlMixin._svc_enableAttributeScopeAdvisorySwitch",
  "enableCallbacks": "hla2010_rti_python.callbacks.PythonRTICallbacksMixin._svc_enableCallbacks",
  "enableInteractionRelevanceAdvisorySwitch": "hla2010_rti_python.support_control.PythonRTISupportControlMixin._svc_enableInteractionRelevanceAdvisorySwitch",
  "enableObjectClassRelevanceAdvisorySwitch": "hla2010_rti_python.support_control.PythonRTISupportControlMixin._svc_enableObjectClassRelevanceAdvisorySwitch",
  "enableTimeConstrained": "hla2010_rti_python.time_public_services.PythonRTITimePublicServicesMixin._svc_enableTimeConstrained",
  "enableTimeRegulation": "hla2010_rti_python.time_public_services.PythonRTITimePublicServicesMixin._svc_enableTimeRegulation",
  "evokeCallback": "hla2010_rti_python.callbacks.PythonRTICallbacksMixin._svc_evokeCallback",
  "evokeMultipleCallbacks": "hla2010_rti_python.callbacks.PythonRTICallbacksMixin._svc_evokeMultipleCallbacks",
  "federateRestoreComplete": "hla2010_rti_python.save_restore_services.PythonRTISaveRestoreServicesMixin._svc_federateRestoreComplete",
  "federateRestoreNotComplete": "hla2010_rti_python.save_restore_services.PythonRTISaveRestoreServicesMixin._svc_federateRestoreNotComplete",
  "federateSaveBegun": "hla2010_rti_python.save_restore_services.PythonRTISaveRestoreServicesMixin._svc_federateSaveBegun",
  "federateSaveComplete": "hla2010_rti_python.save_restore_services.PythonRTISaveRestoreServicesMixin._svc_federateSaveComplete",
  "federateSaveNotComplete": "hla2010_rti_python.save_restore_services.PythonRTISaveRestoreServicesMixin._svc_federateSaveNotComplete",
  "flushQueueRequest": "hla2010_rti_python.time_public_services.PythonRTITimePublicServicesMixin._svc_flushQueueRequest",
  "getAttributeHandle": "hla2010_rti_python.support_lookup.PythonRTISupportLookupMixin._svc_getAttributeHandle",
  "getAttributeHandleFactory": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_getAttributeHandleFactory",
  "getAttributeHandleSetFactory": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_getAttributeHandleSetFactory",
  "getAttributeHandleValueMapFactory": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_getAttributeHandleValueMapFactory",
  "getAttributeName": "hla2010_rti_python.support_lookup.PythonRTISupportLookupMixin._svc_getAttributeName",
  "getAttributeSetRegionSetPairListFactory": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_getAttributeSetRegionSetPairListFactory",
  "getAutomaticResignDirective": "hla2010_rti_python.support_control.PythonRTISupportControlMixin._svc_getAutomaticResignDirective",
  "getAvailableDimensionsForClassAttribute": "hla2010_rti_python.support_control.PythonRTISupportControlMixin._svc_getAvailableDimensionsForClassAttribute",
  "getAvailableDimensionsForInteractionClass": "hla2010_rti_python.support_control.PythonRTISupportControlMixin._svc_getAvailableDimensionsForInteractionClass",
  "getDimensionHandle": "hla2010_rti_python.support_lookup.PythonRTISupportLookupMixin._svc_getDimensionHandle",
  "getDimensionHandleFactory": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_getDimensionHandleFactory",
  "getDimensionHandleSet": "hla2010_rti_python.support_lookup.PythonRTISupportLookupMixin._svc_getDimensionHandleSet",
  "getDimensionHandleSetFactory": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_getDimensionHandleSetFactory",
  "getDimensionName": "hla2010_rti_python.support_lookup.PythonRTISupportLookupMixin._svc_getDimensionName",
  "getDimensionUpperBound": "hla2010_rti_python.ddm_services.PythonRTIDdmServicesMixin._svc_getDimensionUpperBound",
  "getFederateHandle": "hla2010_rti_python.support_lookup.PythonRTISupportLookupMixin._svc_getFederateHandle",
  "getFederateHandleFactory": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_getFederateHandleFactory",
  "getFederateHandleSetFactory": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_getFederateHandleSetFactory",
  "getFederateName": "hla2010_rti_python.support_lookup.PythonRTISupportLookupMixin._svc_getFederateName",
  "getHLAversion": "hla2010_rti_python.support_lookup.PythonRTISupportLookupMixin._svc_getHLAversion",
  "getInteractionClassHandle": "hla2010_rti_python.support_lookup.PythonRTISupportLookupMixin._svc_getInteractionClassHandle",
  "getInteractionClassHandleFactory": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_getInteractionClassHandleFactory",
  "getInteractionClassName": "hla2010_rti_python.support_lookup.PythonRTISupportLookupMixin._svc_getInteractionClassName",
  "getKnownObjectClassHandle": "hla2010_rti_python.support_lookup.PythonRTISupportLookupMixin._svc_getKnownObjectClassHandle",
  "getObjectClassHandle": "hla2010_rti_python.support_lookup.PythonRTISupportLookupMixin._svc_getObjectClassHandle",
  "getObjectClassHandleFactory": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_getObjectClassHandleFactory",
  "getObjectClassName": "hla2010_rti_python.support_lookup.PythonRTISupportLookupMixin._svc_getObjectClassName",
  "getObjectInstanceHandle": "hla2010_rti_python.support_lookup.PythonRTISupportLookupMixin._svc_getObjectInstanceHandle",
  "getObjectInstanceHandleFactory": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_getObjectInstanceHandleFactory",
  "getObjectInstanceName": "hla2010_rti_python.support_lookup.PythonRTISupportLookupMixin._svc_getObjectInstanceName",
  "getOrderName": "hla2010_rti_python.support_control.PythonRTISupportControlMixin._svc_getOrderName",
  "getOrderType": "hla2010_rti_python.support_control.PythonRTISupportControlMixin._svc_getOrderType",
  "getParameterHandle": "hla2010_rti_python.support_lookup.PythonRTISupportLookupMixin._svc_getParameterHandle",
  "getParameterHandleFactory": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_getParameterHandleFactory",
  "getParameterHandleValueMapFactory": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_getParameterHandleValueMapFactory",
  "getParameterName": "hla2010_rti_python.support_lookup.PythonRTISupportLookupMixin._svc_getParameterName",
  "getRangeBounds": "hla2010_rti_python.ddm_services.PythonRTIDdmServicesMixin._svc_getRangeBounds",
  "getRegionHandleSetFactory": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_getRegionHandleSetFactory",
  "getTimeFactory": "hla2010_rti_python.support_lookup.PythonRTISupportLookupMixin._svc_getTimeFactory",
  "getTransportationName": "hla2010_rti_python.support_control.PythonRTISupportControlMixin._svc_getTransportationName",
  "getTransportationType": "hla2010_rti_python.support_control.PythonRTISupportControlMixin._svc_getTransportationType",
  "getTransportationTypeHandle": "hla2010_rti_python.support_lookup.PythonRTISupportLookupMixin._svc_getTransportationTypeHandle",
  "getTransportationTypeHandleFactory": "hla2010_rti_python.support_factories.PythonRTISupportFactoriesMixin._svc_getTransportationTypeHandleFactory",
  "getTransportationTypeName": "hla2010_rti_python.support_lookup.PythonRTISupportLookupMixin._svc_getTransportationTypeName",
  "getUpdateRateValue": "hla2010_rti_python.support_control.PythonRTISupportControlMixin._svc_getUpdateRateValue",
  "getUpdateRateValueForAttribute": "hla2010_rti_python.support_control.PythonRTISupportControlMixin._svc_getUpdateRateValueForAttribute",
  "isAttributeOwnedByFederate": "hla2010_rti_python.ownership_services.PythonRTIOwnershipServicesMixin._svc_isAttributeOwnedByFederate",
  "joinFederationExecution": "hla2010_rti_python.federation_membership.PythonRTIFederationMembershipMixin._svc_joinFederationExecution",
  "listFederationExecutions": "hla2010_rti_python.federation_creation.PythonRTIFederationCreationMixin._svc_listFederationExecutions",
  "localDeleteObjectInstance": "hla2010_rti_python.object_delivery_control.PythonRTIObjectDeliveryControlMixin._svc_localDeleteObjectInstance",
  "modifyLookahead": "hla2010_rti_python.time_public_services.PythonRTITimePublicServicesMixin._svc_modifyLookahead",
  "negotiatedAttributeOwnershipDivestiture": "hla2010_rti_python.ownership_services.PythonRTIOwnershipServicesMixin._svc_negotiatedAttributeOwnershipDivestiture",
  "nextMessageRequest": "hla2010_rti_python.time_public_services.PythonRTITimePublicServicesMixin._svc_nextMessageRequest",
  "nextMessageRequestAvailable": "hla2010_rti_python.time_public_services.PythonRTITimePublicServicesMixin._svc_nextMessageRequestAvailable",
  "normalizeFederateHandle": "hla2010_rti_python.support_control.PythonRTISupportControlMixin._svc_normalizeFederateHandle",
  "normalizeServiceGroup": "hla2010_rti_python.support_control.PythonRTISupportControlMixin._svc_normalizeServiceGroup",
  "publishInteractionClass": "hla2010_rti_python.declaration.PythonRTIDeclarationMixin._svc_publishInteractionClass",
  "publishObjectClassAttributes": "hla2010_rti_python.declaration.PythonRTIDeclarationMixin._svc_publishObjectClassAttributes",
  "queryAttributeOwnership": "hla2010_rti_python.ownership_services.PythonRTIOwnershipServicesMixin._svc_queryAttributeOwnership",
  "queryAttributeTransportationType": "hla2010_rti_python.object_delivery_control.PythonRTIObjectDeliveryControlMixin._svc_queryAttributeTransportationType",
  "queryFederationRestoreStatus": "hla2010_rti_python.save_restore_services.PythonRTISaveRestoreServicesMixin._svc_queryFederationRestoreStatus",
  "queryFederationSaveStatus": "hla2010_rti_python.save_restore_services.PythonRTISaveRestoreServicesMixin._svc_queryFederationSaveStatus",
  "queryGALT": "hla2010_rti_python.time_public_services.PythonRTITimePublicServicesMixin._svc_queryGALT",
  "queryInteractionTransportationType": "hla2010_rti_python.object_delivery_control.PythonRTIObjectDeliveryControlMixin._svc_queryInteractionTransportationType",
  "queryLITS": "hla2010_rti_python.time_public_services.PythonRTITimePublicServicesMixin._svc_queryLITS",
  "queryLogicalTime": "hla2010_rti_python.time_public_services.PythonRTITimePublicServicesMixin._svc_queryLogicalTime",
  "queryLookahead": "hla2010_rti_python.time_public_services.PythonRTITimePublicServicesMixin._svc_queryLookahead",
  "registerFederationSynchronizationPoint": "hla2010_rti_python.federation_sync.PythonRTIFederationSyncMixin._svc_registerFederationSynchronizationPoint",
  "registerObjectInstance": "hla2010_rti_python.object.PythonRTIObjectMixin._svc_registerObjectInstance",
  "registerObjectInstanceWithRegions": "hla2010_rti_python.ddm_services.PythonRTIDdmServicesMixin._svc_registerObjectInstanceWithRegions",
  "releaseMultipleObjectInstanceName": "hla2010_rti_python.object.PythonRTIObjectMixin._svc_releaseMultipleObjectInstanceName",
  "releaseObjectInstanceName": "hla2010_rti_python.object.PythonRTIObjectMixin._svc_releaseObjectInstanceName",
  "requestAttributeTransportationTypeChange": "hla2010_rti_python.object_delivery_control.PythonRTIObjectDeliveryControlMixin._svc_requestAttributeTransportationTypeChange",
  "requestAttributeValueUpdate": "hla2010_rti_python.object_delivery_attributes.PythonRTIObjectAttributeDeliveryMixin._svc_requestAttributeValueUpdate",
  "requestAttributeValueUpdateWithRegions": "hla2010_rti_python.ddm_services.PythonRTIDdmServicesMixin._svc_requestAttributeValueUpdateWithRegions",
  "requestFederationRestore": "hla2010_rti_python.save_restore_services.PythonRTISaveRestoreServicesMixin._svc_requestFederationRestore",
  "requestFederationSave": "hla2010_rti_python.save_restore_services.PythonRTISaveRestoreServicesMixin._svc_requestFederationSave",
  "requestInteractionTransportationTypeChange": "hla2010_rti_python.object_delivery_control.PythonRTIObjectDeliveryControlMixin._svc_requestInteractionTransportationTypeChange",
  "reserveMultipleObjectInstanceName": "hla2010_rti_python.object.PythonRTIObjectMixin._svc_reserveMultipleObjectInstanceName",
  "reserveObjectInstanceName": "hla2010_rti_python.object.PythonRTIObjectMixin._svc_reserveObjectInstanceName",
  "resignFederationExecution": "hla2010_rti_python.federation_membership.PythonRTIFederationMembershipMixin._svc_resignFederationExecution",
  "retract": "hla2010_rti_python.time_public_services.PythonRTITimePublicServicesMixin._svc_retract",
  "sendInteraction": "hla2010_rti_python.object_delivery_interactions.PythonRTIObjectInteractionDeliveryMixin._svc_sendInteraction",
  "sendInteractionWithRegions": "hla2010_rti_python.ddm_services.PythonRTIDdmServicesMixin._svc_sendInteractionWithRegions",
  "setAutomaticResignDirective": "hla2010_rti_python.support_control.PythonRTISupportControlMixin._svc_setAutomaticResignDirective",
  "setRangeBounds": "hla2010_rti_python.ddm_services.PythonRTIDdmServicesMixin._svc_setRangeBounds",
  "subscribeInteractionClass": "hla2010_rti_python.declaration.PythonRTIDeclarationMixin._svc_subscribeInteractionClass",
  "subscribeInteractionClassPassively": "hla2010_rti_python.declaration.PythonRTIDeclarationMixin._svc_subscribeInteractionClassPassively",
  "subscribeInteractionClassPassivelyWithRegions": "hla2010_rti_python.ddm_services.PythonRTIDdmServicesMixin._svc_subscribeInteractionClassPassivelyWithRegions",
  "subscribeInteractionClassWithRegions": "hla2010_rti_python.ddm_services.PythonRTIDdmServicesMixin._svc_subscribeInteractionClassWithRegions",
  "subscribeObjectClassAttributes": "hla2010_rti_python.declaration.PythonRTIDeclarationMixin._svc_subscribeObjectClassAttributes",
  "subscribeObjectClassAttributesPassively": "hla2010_rti_python.declaration.PythonRTIDeclarationMixin._svc_subscribeObjectClassAttributesPassively",
  "subscribeObjectClassAttributesPassivelyWithRegions": "hla2010_rti_python.ddm_services.PythonRTIDdmServicesMixin._svc_subscribeObjectClassAttributesPassivelyWithRegions",
  "subscribeObjectClassAttributesWithRegions": "hla2010_rti_python.ddm_services.PythonRTIDdmServicesMixin._svc_subscribeObjectClassAttributesWithRegions",
  "synchronizationPointAchieved": "hla2010_rti_python.federation_sync.PythonRTIFederationSyncMixin._svc_synchronizationPointAchieved",
  "timeAdvanceRequest": "hla2010_rti_python.time_public_services.PythonRTITimePublicServicesMixin._svc_timeAdvanceRequest",
  "timeAdvanceRequestAvailable": "hla2010_rti_python.time_public_services.PythonRTITimePublicServicesMixin._svc_timeAdvanceRequestAvailable",
  "unassociateRegionsForUpdates": "hla2010_rti_python.ddm_services.PythonRTIDdmServicesMixin._svc_unassociateRegionsForUpdates",
  "unconditionalAttributeOwnershipDivestiture": "hla2010_rti_python.ownership_services.PythonRTIOwnershipServicesMixin._svc_unconditionalAttributeOwnershipDivestiture",
  "unpublishInteractionClass": "hla2010_rti_python.declaration.PythonRTIDeclarationMixin._svc_unpublishInteractionClass",
  "unpublishObjectClass": "hla2010_rti_python.declaration.PythonRTIDeclarationMixin._svc_unpublishObjectClass",
  "unpublishObjectClassAttributes": "hla2010_rti_python.declaration.PythonRTIDeclarationMixin._svc_unpublishObjectClassAttributes",
  "unsubscribeInteractionClass": "hla2010_rti_python.declaration.PythonRTIDeclarationMixin._svc_unsubscribeInteractionClass",
  "unsubscribeInteractionClassWithRegions": "hla2010_rti_python.ddm_services.PythonRTIDdmServicesMixin._svc_unsubscribeInteractionClassWithRegions",
  "unsubscribeObjectClass": "hla2010_rti_python.declaration.PythonRTIDeclarationMixin._svc_unsubscribeObjectClass",
  "unsubscribeObjectClassAttributes": "hla2010_rti_python.declaration.PythonRTIDeclarationMixin._svc_unsubscribeObjectClassAttributes",
  "unsubscribeObjectClassAttributesWithRegions": "hla2010_rti_python.ddm_services.PythonRTIDdmServicesMixin._svc_unsubscribeObjectClassAttributesWithRegions",
  "updateAttributeValues": "hla2010_rti_python.object_delivery_attributes.PythonRTIObjectAttributeDeliveryMixin._svc_updateAttributeValues"
}

PYTHON_RTI_NON_RTI_SERVICE_REASONS: dict[str, str] = {
  "provideAttributeValueUpdate": "federate callback delivery helper",
  "startRegistrationForObjectClass": "federate callback delivery helper",
  "stopRegistrationForObjectClass": "federate callback delivery helper",
  "turnInteractionsOff": "federate callback delivery helper",
  "turnInteractionsOn": "federate callback delivery helper",
  "turnUpdatesOffForObjectInstance": "federate callback delivery helper",
  "turnUpdatesOnForObjectInstance": "federate callback delivery helper"
}

__all__ = ["PYTHON_RTI_NON_RTI_SERVICE_REASONS", "PYTHON_RTI_SERVICE_REGISTRY"]
