from __future__ import annotations

from typing import Protocol, Sequence, Set, overload

from .datatypes import *
from .enums import *
from .handles import *
from .logical_time import *

def lower_camel_to_snake(name: str) -> str: ...

class FederateAmbassador(Protocol):
    """Typed Python protocol for IEEE 1516.1-2010 FederateAmbassador.

    Source trace: Java hla/rti1516e and C++ RTI API files from the supplied 1516.1-2010 bundle.
    """

    # Source: Java/C++ §4.4. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def connectionLost(self, faultDescription: str) -> None: ...

    # Source: Java/C++ §4.8. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def reportFederationExecutions(self, theFederationExecutionInformationSet: FederationExecutionInformationSet) -> None: ...

    # Source: Java/C++ §4.12. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def synchronizationPointRegistrationSucceeded(self, synchronizationPointLabel: str) -> None: ...

    # Source: Java/C++ §4.12. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def synchronizationPointRegistrationFailed(self, synchronizationPointLabel: str, reason: SynchronizationPointFailureReason) -> None: ...

    # Source: Java/C++ §4.13. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def announceSynchronizationPoint(self, synchronizationPointLabel: str, userSuppliedTag: bytes) -> None: ...

    # Source: Java/C++ §4.15. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def federationSynchronized(self, synchronizationPointLabel: str, failedToSyncSet: FederateHandleSet) -> None: ...

    # Source: Java/C++ §4.17. Java overloads: 2; C++ overloads: 2. Throws: FederateInternalError.
    @overload
    def initiateFederateSave(self, label: str) -> None: ...
    @overload
    def initiateFederateSave(self, label: str, time: LogicalTime) -> None: ...

    # Source: Java/C++ §4.20. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def federationSaved(self) -> None: ...

    # Source: Java/C++ §4.20. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def federationNotSaved(self, reason: SaveFailureReason) -> None: ...

    # Source: Java/C++ §4.23. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def federationSaveStatusResponse(self, response: Sequence[FederateHandleSaveStatusPair]) -> None: ...

    # Source: Java/C++ §4.25. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def requestFederationRestoreSucceeded(self, label: str) -> None: ...

    # Source: Java/C++ §4.25. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def requestFederationRestoreFailed(self, label: str) -> None: ...

    # Source: Java/C++ §4.26. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def federationRestoreBegun(self) -> None: ...

    # Source: Java/C++ §4.27. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def initiateFederateRestore(self, label: str, federateName: str, federateHandle: FederateHandle) -> None: ...

    # Source: Java/C++ §4.29. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def federationRestored(self) -> None: ...

    # Source: Java/C++ §4.29. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def federationNotRestored(self, reason: RestoreFailureReason) -> None: ...

    # Source: Java/C++ §4.32. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def federationRestoreStatusResponse(self, response: Sequence[FederateRestoreStatus]) -> None: ...

    # Source: Java/C++ §5.10. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def startRegistrationForObjectClass(self, theClass: ObjectClassHandle) -> None: ...

    # Source: Java/C++ §5.11. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def stopRegistrationForObjectClass(self, theClass: ObjectClassHandle) -> None: ...

    # Source: Java/C++ §5.12. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def turnInteractionsOn(self, theHandle: InteractionClassHandle) -> None: ...

    # Source: Java/C++ §5.13. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def turnInteractionsOff(self, theHandle: InteractionClassHandle) -> None: ...

    # Source: Java/C++ §6.3. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def objectInstanceNameReservationSucceeded(self, objectName: str) -> None: ...

    # Source: Java/C++ §6.3. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def objectInstanceNameReservationFailed(self, objectName: str) -> None: ...

    # Source: Java/C++ §6.6. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def multipleObjectInstanceNameReservationSucceeded(self, objectNames: Set[str]) -> None: ...

    # Source: Java/C++ §6.6. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def multipleObjectInstanceNameReservationFailed(self, objectNames: Set[str]) -> None: ...

    # Source: Java/C++ §6.9. Java overloads: 2; C++ overloads: 2. Throws: FederateInternalError.
    @overload
    def discoverObjectInstance(self, theObject: ObjectInstanceHandle, theObjectClass: ObjectClassHandle, objectName: str) -> None: ...
    @overload
    def discoverObjectInstance(self, theObject: ObjectInstanceHandle, theObjectClass: ObjectClassHandle, objectName: str, producingFederate: FederateHandle) -> None: ...

    # Source: Java/C++ §6.11. Java overloads: 3; C++ overloads: 3. Throws: FederateInternalError.
    @overload
    def reflectAttributeValues(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleValueMap, userSuppliedTag: bytes, sentOrdering: OrderType, theTransport: TransportationTypeHandle, reflectInfo: SupplementalReflectInfo) -> None: ...
    @overload
    def reflectAttributeValues(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleValueMap, userSuppliedTag: bytes, sentOrdering: OrderType, theTransport: TransportationTypeHandle, theTime: LogicalTime, receivedOrdering: OrderType, reflectInfo: SupplementalReflectInfo) -> None: ...
    @overload
    def reflectAttributeValues(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleValueMap, userSuppliedTag: bytes, sentOrdering: OrderType, theTransport: TransportationTypeHandle, theTime: LogicalTime, receivedOrdering: OrderType, retractionHandle: MessageRetractionHandle, reflectInfo: SupplementalReflectInfo) -> None: ...

    # Source: Java/C++ §6.13. Java overloads: 3; C++ overloads: 3. Throws: FederateInternalError.
    @overload
    def receiveInteraction(self, interactionClass: InteractionClassHandle, theParameters: ParameterHandleValueMap, userSuppliedTag: bytes, sentOrdering: OrderType, theTransport: TransportationTypeHandle, receiveInfo: SupplementalReceiveInfo) -> None: ...
    @overload
    def receiveInteraction(self, interactionClass: InteractionClassHandle, theParameters: ParameterHandleValueMap, userSuppliedTag: bytes, sentOrdering: OrderType, theTransport: TransportationTypeHandle, theTime: LogicalTime, receivedOrdering: OrderType, receiveInfo: SupplementalReceiveInfo) -> None: ...
    @overload
    def receiveInteraction(self, interactionClass: InteractionClassHandle, theParameters: ParameterHandleValueMap, userSuppliedTag: bytes, sentOrdering: OrderType, theTransport: TransportationTypeHandle, theTime: LogicalTime, receivedOrdering: OrderType, retractionHandle: MessageRetractionHandle, receiveInfo: SupplementalReceiveInfo) -> None: ...

    # Source: Java/C++ §6.15. Java overloads: 3; C++ overloads: 3. Throws: FederateInternalError.
    @overload
    def removeObjectInstance(self, theObject: ObjectInstanceHandle, userSuppliedTag: bytes, sentOrdering: OrderType, removeInfo: SupplementalRemoveInfo) -> None: ...
    @overload
    def removeObjectInstance(self, theObject: ObjectInstanceHandle, userSuppliedTag: bytes, sentOrdering: OrderType, theTime: LogicalTime, receivedOrdering: OrderType, removeInfo: SupplementalRemoveInfo) -> None: ...
    @overload
    def removeObjectInstance(self, theObject: ObjectInstanceHandle, userSuppliedTag: bytes, sentOrdering: OrderType, theTime: LogicalTime, receivedOrdering: OrderType, retractionHandle: MessageRetractionHandle, removeInfo: SupplementalRemoveInfo) -> None: ...

    # Source: Java/C++ §6.17. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def attributesInScope(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleSet) -> None: ...

    # Source: Java/C++ §6.18. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def attributesOutOfScope(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleSet) -> None: ...

    # Source: Java/C++ §6.20. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def provideAttributeValueUpdate(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleSet, userSuppliedTag: bytes) -> None: ...

    # Source: Java/C++ §6.21. Java overloads: 2; C++ overloads: 2. Throws: FederateInternalError.
    @overload
    def turnUpdatesOnForObjectInstance(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleSet) -> None: ...
    @overload
    def turnUpdatesOnForObjectInstance(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleSet, updateRateDesignator: str) -> None: ...

    # Source: Java/C++ §6.22. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def turnUpdatesOffForObjectInstance(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleSet) -> None: ...

    # Source: Java/C++ §6.24. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def confirmAttributeTransportationTypeChange(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleSet, theTransportation: TransportationTypeHandle) -> None: ...

    # Source: Java/C++ §6.26. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def reportAttributeTransportationType(self, theObject: ObjectInstanceHandle, theAttribute: AttributeHandle, theTransportation: TransportationTypeHandle) -> None: ...

    # Source: Java/C++ §6.28. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def confirmInteractionTransportationTypeChange(self, theInteraction: InteractionClassHandle, theTransportation: TransportationTypeHandle) -> None: ...

    # Source: Java/C++ §6.30. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def reportInteractionTransportationType(self, theFederate: FederateHandle, theInteraction: InteractionClassHandle, theTransportation: TransportationTypeHandle) -> None: ...

    # Source: Java/C++ §7.4. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def requestAttributeOwnershipAssumption(self, theObject: ObjectInstanceHandle, offeredAttributes: AttributeHandleSet, userSuppliedTag: bytes) -> None: ...

    # Source: Java/C++ §7.5. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def requestDivestitureConfirmation(self, theObject: ObjectInstanceHandle, offeredAttributes: AttributeHandleSet) -> None: ...

    # Source: Java/C++ §7.7. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def attributeOwnershipAcquisitionNotification(self, theObject: ObjectInstanceHandle, securedAttributes: AttributeHandleSet, userSuppliedTag: bytes) -> None: ...

    # Source: Java/C++ §7.10. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def attributeOwnershipUnavailable(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleSet) -> None: ...

    # Source: Java/C++ §7.11. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def requestAttributeOwnershipRelease(self, theObject: ObjectInstanceHandle, candidateAttributes: AttributeHandleSet, userSuppliedTag: bytes) -> None: ...

    # Source: Java/C++ §7.16. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def confirmAttributeOwnershipAcquisitionCancellation(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleSet) -> None: ...

    # Source: Java/C++ §7.18. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def informAttributeOwnership(self, theObject: ObjectInstanceHandle, theAttribute: AttributeHandle, theOwner: FederateHandle) -> None: ...

    # Source: Java/C++ §7.18. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def attributeIsNotOwned(self, theObject: ObjectInstanceHandle, theAttribute: AttributeHandle) -> None: ...

    # Source: Java/C++ §7.18. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def attributeIsOwnedByRTI(self, theObject: ObjectInstanceHandle, theAttribute: AttributeHandle) -> None: ...

    # Source: Java/C++ §8.3. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def timeRegulationEnabled(self, time: LogicalTime) -> None: ...

    # Source: Java/C++ §8.6. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def timeConstrainedEnabled(self, time: LogicalTime) -> None: ...

    # Source: Java/C++ §8.13. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def timeAdvanceGrant(self, theTime: LogicalTime) -> None: ...

    # Source: Java/C++ §8.22. Java overloads: 1; C++ overloads: 1. Throws: FederateInternalError.
    def requestRetraction(self, theHandle: MessageRetractionHandle) -> None: ...

class NullFederateAmbassador(FederateAmbassador):
    def __getattr__(self, name: str): ...
