from __future__ import annotations

from typing import Protocol, Sequence, Set, overload

from .datatypes import *
from .enums import *
from .federate_ambassador import FederateAmbassador
from .handle_factory import *
from .handles import *
from .logical_time import *

class RTIambassador(Protocol):
    """Typed Python protocol for IEEE 1516.1-2010 RTIambassador.

    Source trace: Java hla/rti1516e and C++ RTI API files from the supplied 1516.1-2010 bundle.
    """

    # Source: Java/C++ §4.2. Java overloads: 2; C++ overloads: 1. Throws: ConnectionFailed, InvalidLocalSettingsDesignator, UnsupportedCallbackModel, AlreadyConnected, CallNotAllowedFromWithinCallback, RTIinternalError.
    @overload
    def connect(self, federateReference: FederateAmbassador, callbackModel: CallbackModel, localSettingsDesignator: str) -> None: ...
    @overload
    def connect(self, federateReference: FederateAmbassador, callbackModel: CallbackModel) -> None: ...

    # Source: Java/C++ §4.3. Java overloads: 1; C++ overloads: 1. Throws: FederateIsExecutionMember, CallNotAllowedFromWithinCallback, RTIinternalError.
    def disconnect(self) -> None: ...

    # Source: Java/C++ §4.5. Java overloads: 5; C++ overloads: 2. Throws: CouldNotCreateLogicalTimeFactory, InconsistentFDD, ErrorReadingFDD, CouldNotOpenFDD, ErrorReadingMIM, CouldNotOpenMIM; ….
    @overload
    def createFederationExecution(self, federationExecutionName: str, fomModule: str) -> None: ...
    @overload
    def createFederationExecution(self, federationExecutionName: str, fomModule: str, logicalTimeImplementationName: str) -> None: ...
    @overload
    def createFederationExecution(self, federationExecutionName: str, fomModules: Sequence[str]) -> None: ...
    @overload
    def createFederationExecution(self, federationExecutionName: str, fomModules: Sequence[str], *, logicalTimeImplementationName: str) -> None: ...
    @overload
    def createFederationExecution(self, federationExecutionName: str, fomModules: Sequence[str], *, mimModule: str) -> None: ...
    @overload
    def createFederationExecution(self, federationExecutionName: str, fomModules: Sequence[str], *, mimModule: str, logicalTimeImplementationName: str) -> None: ...

    # Source: Java/C++ §4.6. Java overloads: 1; C++ overloads: 1. Throws: FederatesCurrentlyJoined, FederationExecutionDoesNotExist, NotConnected, RTIinternalError.
    def destroyFederationExecution(self, federationExecutionName: str) -> None: ...

    # Source: Java/C++ §4.7. Java overloads: 1; C++ overloads: 1. Throws: NotConnected, RTIinternalError.
    def listFederationExecutions(self) -> None: ...

    # Source: Java/C++ §4.9. Java overloads: 4; C++ overloads: 2. Throws: CouldNotCreateLogicalTimeFactory, FederateNameAlreadyInUse, FederationExecutionDoesNotExist, InconsistentFDD, ErrorReadingFDD, CouldNotOpenFDD; ….
    @overload
    def joinFederationExecution(self, *, federateType: str, federationExecutionName: str) -> FederateHandle: ...
    @overload
    def joinFederationExecution(self, *, federateType: str, federationExecutionName: str, additionalFomModules: Sequence[str]) -> FederateHandle: ...
    @overload
    def joinFederationExecution(self, *, federateName: str, federateType: str, federationExecutionName: str) -> FederateHandle: ...
    @overload
    def joinFederationExecution(self, *, federateName: str, federateType: str, federationExecutionName: str, additionalFomModules: Sequence[str]) -> FederateHandle: ...

    # Source: Java/C++ §4.10. Java overloads: 1; C++ overloads: 1. Throws: InvalidResignAction, OwnershipAcquisitionPending, FederateOwnsAttributes, FederateNotExecutionMember, NotConnected, CallNotAllowedFromWithinCallback; ….
    def resignFederationExecution(self, resignAction: ResignAction) -> None: ...

    # Source: Java/C++ §4.11. Java overloads: 2; C++ overloads: 2. Throws: SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError, InvalidFederateHandle.
    @overload
    def registerFederationSynchronizationPoint(self, synchronizationPointLabel: str, userSuppliedTag: bytes) -> None: ...
    @overload
    def registerFederationSynchronizationPoint(self, synchronizationPointLabel: str, userSuppliedTag: bytes, synchronizationSet: FederateHandleSet) -> None: ...

    # Source: Java/C++ §4.14. Java overloads: 2; C++ overloads: 1. Throws: SynchronizationPointLabelNotAnnounced, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    @overload
    def synchronizationPointAchieved(self, synchronizationPointLabel: str) -> None: ...
    @overload
    def synchronizationPointAchieved(self, synchronizationPointLabel: str, successIndicator: bool) -> None: ...

    # Source: Java/C++ §4.16. Java overloads: 2; C++ overloads: 2. Throws: SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError, LogicalTimeAlreadyPassed; ….
    @overload
    def requestFederationSave(self, label: str) -> None: ...
    @overload
    def requestFederationSave(self, label: str, theTime: LogicalTime) -> None: ...

    # Source: Java/C++ §4.18. Java overloads: 1; C++ overloads: 1. Throws: SaveNotInitiated, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def federateSaveBegun(self) -> None: ...

    # Source: Java/C++ §4.19. Java overloads: 1; C++ overloads: 1. Throws: FederateHasNotBegunSave, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def federateSaveComplete(self) -> None: ...

    # Source: Java/C++ §4.19. Java overloads: 1; C++ overloads: 1. Throws: FederateHasNotBegunSave, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def federateSaveNotComplete(self) -> None: ...

    # Source: Java/C++ §4.21. Java overloads: 1; C++ overloads: 1. Throws: SaveNotInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def abortFederationSave(self) -> None: ...

    # Source: Java/C++ §4.22. Java overloads: 1; C++ overloads: 1. Throws: RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def queryFederationSaveStatus(self) -> None: ...

    # Source: Java/C++ §4.24. Java overloads: 1; C++ overloads: 1. Throws: SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def requestFederationRestore(self, label: str) -> None: ...

    # Source: Java/C++ §4.28. Java overloads: 1; C++ overloads: 1. Throws: RestoreNotRequested, SaveInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def federateRestoreComplete(self) -> None: ...

    # Source: Java/C++ §4.28. Java overloads: 1; C++ overloads: 1. Throws: RestoreNotRequested, SaveInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def federateRestoreNotComplete(self) -> None: ...

    # Source: Java/C++ §4.30. Java overloads: 1; C++ overloads: 1. Throws: RestoreNotInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def abortFederationRestore(self) -> None: ...

    # Source: Java/C++ §4.31. Java overloads: 1; C++ overloads: 1. Throws: SaveInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def queryFederationRestoreStatus(self) -> None: ...

    # Source: Java/C++ §5.2. Java overloads: 1; C++ overloads: 1. Throws: AttributeNotDefined, ObjectClassNotDefined, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected; ….
    def publishObjectClassAttributes(self, theClass: ObjectClassHandle, attributeList: AttributeHandleSet) -> None: ...

    # Source: Java/C++ §5.3. Java overloads: 1; C++ overloads: 1. Throws: OwnershipAcquisitionPending, ObjectClassNotDefined, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected; ….
    def unpublishObjectClass(self, theClass: ObjectClassHandle) -> None: ...

    # Source: Java/C++ §5.3. Java overloads: 1; C++ overloads: 1. Throws: OwnershipAcquisitionPending, AttributeNotDefined, ObjectClassNotDefined, SaveInProgress, RestoreInProgress, FederateNotExecutionMember; ….
    def unpublishObjectClassAttributes(self, theClass: ObjectClassHandle, attributeList: AttributeHandleSet) -> None: ...

    # Source: Java/C++ §5.4. Java overloads: 1; C++ overloads: 1. Throws: InteractionClassNotDefined, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def publishInteractionClass(self, theInteraction: InteractionClassHandle) -> None: ...

    # Source: Java/C++ §5.5. Java overloads: 1; C++ overloads: 1. Throws: InteractionClassNotDefined, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def unpublishInteractionClass(self, theInteraction: InteractionClassHandle) -> None: ...

    # Source: Java/C++ §5.6. Java overloads: 2; C++ overloads: 1. Throws: AttributeNotDefined, ObjectClassNotDefined, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected; ….
    @overload
    def subscribeObjectClassAttributes(self, theClass: ObjectClassHandle, attributeList: AttributeHandleSet) -> None: ...
    @overload
    def subscribeObjectClassAttributes(self, theClass: ObjectClassHandle, attributeList: AttributeHandleSet, updateRateDesignator: str) -> None: ...

    # Source: Java §5.6. Java overloads: 2; C++ overloads: 0. Throws: AttributeNotDefined, ObjectClassNotDefined, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected; ….
    @overload
    def subscribeObjectClassAttributesPassively(self, theClass: ObjectClassHandle, attributeList: AttributeHandleSet) -> None: ...
    @overload
    def subscribeObjectClassAttributesPassively(self, theClass: ObjectClassHandle, attributeList: AttributeHandleSet, updateRateDesignator: str) -> None: ...

    # Source: Java/C++ §5.7. Java overloads: 1; C++ overloads: 1. Throws: ObjectClassNotDefined, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def unsubscribeObjectClass(self, theClass: ObjectClassHandle) -> None: ...

    # Source: Java/C++ §5.7. Java overloads: 1; C++ overloads: 1. Throws: AttributeNotDefined, ObjectClassNotDefined, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected; ….
    def unsubscribeObjectClassAttributes(self, theClass: ObjectClassHandle, attributeList: AttributeHandleSet) -> None: ...

    # Source: Java/C++ §5.8. Java overloads: 1; C++ overloads: 1. Throws: FederateServiceInvocationsAreBeingReportedViaMOM, InteractionClassNotDefined, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected; ….
    def subscribeInteractionClass(self, theClass: InteractionClassHandle) -> None: ...

    # Source: Java §5.8. Java overloads: 1; C++ overloads: 0. Throws: FederateServiceInvocationsAreBeingReportedViaMOM, InteractionClassNotDefined, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected; ….
    def subscribeInteractionClassPassively(self, theClass: InteractionClassHandle) -> None: ...

    # Source: Java/C++ §5.9. Java overloads: 1; C++ overloads: 1. Throws: InteractionClassNotDefined, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def unsubscribeInteractionClass(self, theClass: InteractionClassHandle) -> None: ...

    # Source: Java/C++ §6.2. Java overloads: 1; C++ overloads: 1. Throws: IllegalName, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def reserveObjectInstanceName(self, theObjectName: str) -> None: ...

    # Source: Java/C++ §6.4. Java overloads: 1; C++ overloads: 1. Throws: ObjectInstanceNameNotReserved, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def releaseObjectInstanceName(self, theObjectInstanceName: str) -> None: ...

    # Source: Java/C++ §6.5. Java overloads: 1; C++ overloads: 1. Throws: IllegalName, NameSetWasEmpty, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected; ….
    def reserveMultipleObjectInstanceName(self, theObjectNames: Set[str]) -> None: ...

    # Source: Java/C++ §6.7. Java overloads: 1; C++ overloads: 1. Throws: ObjectInstanceNameNotReserved, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def releaseMultipleObjectInstanceName(self, theObjectNames: Set[str]) -> None: ...

    # Source: Java/C++ §6.8. Java overloads: 2; C++ overloads: 2. Throws: ObjectClassNotPublished, ObjectClassNotDefined, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected; ….
    @overload
    def registerObjectInstance(self, theClass: ObjectClassHandle) -> ObjectInstanceHandle: ...
    @overload
    def registerObjectInstance(self, theClass: ObjectClassHandle, theObjectName: str) -> ObjectInstanceHandle: ...

    # Source: Java/C++ §6.10. Java overloads: 2; C++ overloads: 2. Throws: AttributeNotOwned, AttributeNotDefined, ObjectInstanceNotKnown, SaveInProgress, RestoreInProgress, FederateNotExecutionMember; ….
    @overload
    def updateAttributeValues(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleValueMap, userSuppliedTag: bytes) -> None: ...
    @overload
    def updateAttributeValues(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleValueMap, userSuppliedTag: bytes, theTime: LogicalTime) -> MessageRetractionReturn: ...

    # Source: Java/C++ §6.12. Java overloads: 2; C++ overloads: 2. Throws: InteractionClassNotPublished, InteractionParameterNotDefined, InteractionClassNotDefined, SaveInProgress, RestoreInProgress, FederateNotExecutionMember; ….
    @overload
    def sendInteraction(self, theInteraction: InteractionClassHandle, theParameters: ParameterHandleValueMap, userSuppliedTag: bytes) -> None: ...
    @overload
    def sendInteraction(self, theInteraction: InteractionClassHandle, theParameters: ParameterHandleValueMap, userSuppliedTag: bytes, theTime: LogicalTime) -> MessageRetractionReturn: ...

    # Source: Java/C++ §6.14. Java overloads: 2; C++ overloads: 2. Throws: DeletePrivilegeNotHeld, ObjectInstanceNotKnown, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected; ….
    @overload
    def deleteObjectInstance(self, objectHandle: ObjectInstanceHandle, userSuppliedTag: bytes) -> None: ...
    @overload
    def deleteObjectInstance(self, objectHandle: ObjectInstanceHandle, userSuppliedTag: bytes, theTime: LogicalTime) -> MessageRetractionReturn: ...

    # Source: Java/C++ §6.16. Java overloads: 1; C++ overloads: 1. Throws: OwnershipAcquisitionPending, FederateOwnsAttributes, ObjectInstanceNotKnown, SaveInProgress, RestoreInProgress, FederateNotExecutionMember; ….
    def localDeleteObjectInstance(self, objectHandle: ObjectInstanceHandle) -> None: ...

    # Source: Java/C++ §6.19. Java overloads: 2; C++ overloads: 2. Throws: AttributeNotDefined, ObjectInstanceNotKnown, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected; ….
    @overload
    def requestAttributeValueUpdate(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleSet, userSuppliedTag: bytes) -> None: ...
    @overload
    def requestAttributeValueUpdate(self, theClass: ObjectClassHandle, theAttributes: AttributeHandleSet, userSuppliedTag: bytes) -> None: ...

    # Source: Java/C++ §6.23. Java overloads: 1; C++ overloads: 1. Throws: AttributeAlreadyBeingChanged, AttributeNotOwned, AttributeNotDefined, ObjectInstanceNotKnown, InvalidTransportationType, SaveInProgress; ….
    def requestAttributeTransportationTypeChange(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleSet, theType: TransportationTypeHandle) -> None: ...

    # Source: Java/C++ §6.25. Java overloads: 1; C++ overloads: 1. Throws: AttributeNotDefined, ObjectInstanceNotKnown, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected; ….
    def queryAttributeTransportationType(self, theObject: ObjectInstanceHandle, theAttribute: AttributeHandle) -> None: ...

    # Source: Java/C++ §6.27. Java overloads: 1; C++ overloads: 1. Throws: InteractionClassAlreadyBeingChanged, InteractionClassNotPublished, InteractionClassNotDefined, InvalidTransportationType, SaveInProgress, RestoreInProgress; ….
    def requestInteractionTransportationTypeChange(self, theClass: InteractionClassHandle, theType: TransportationTypeHandle) -> None: ...

    # Source: Java/C++ §6.29. Java overloads: 1; C++ overloads: 1. Throws: InteractionClassNotDefined, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def queryInteractionTransportationType(self, theFederate: FederateHandle, theInteraction: InteractionClassHandle) -> None: ...

    # Source: Java/C++ §7.2. Java overloads: 1; C++ overloads: 1. Throws: AttributeNotOwned, AttributeNotDefined, ObjectInstanceNotKnown, SaveInProgress, RestoreInProgress, FederateNotExecutionMember; ….
    def unconditionalAttributeOwnershipDivestiture(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleSet) -> None: ...

    # Source: Java/C++ §7.3. Java overloads: 1; C++ overloads: 1. Throws: AttributeAlreadyBeingDivested, AttributeNotOwned, AttributeNotDefined, ObjectInstanceNotKnown, SaveInProgress, RestoreInProgress; ….
    def negotiatedAttributeOwnershipDivestiture(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleSet, userSuppliedTag: bytes) -> None: ...

    # Source: Java/C++ §7.6. Java overloads: 1; C++ overloads: 1. Throws: NoAcquisitionPending, AttributeDivestitureWasNotRequested, AttributeNotOwned, AttributeNotDefined, ObjectInstanceNotKnown, SaveInProgress; ….
    def confirmDivestiture(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleSet, userSuppliedTag: bytes) -> None: ...

    # Source: Java/C++ §7.8. Java overloads: 1; C++ overloads: 1. Throws: AttributeNotPublished, ObjectClassNotPublished, FederateOwnsAttributes, AttributeNotDefined, ObjectInstanceNotKnown, SaveInProgress; ….
    def attributeOwnershipAcquisition(self, theObject: ObjectInstanceHandle, desiredAttributes: AttributeHandleSet, userSuppliedTag: bytes) -> None: ...

    # Source: Java/C++ §7.9. Java overloads: 1; C++ overloads: 1. Throws: AttributeAlreadyBeingAcquired, AttributeNotPublished, ObjectClassNotPublished, FederateOwnsAttributes, AttributeNotDefined, ObjectInstanceNotKnown; ….
    def attributeOwnershipAcquisitionIfAvailable(self, theObject: ObjectInstanceHandle, desiredAttributes: AttributeHandleSet) -> None: ...

    # Source: Java/C++ §7.12. Java overloads: 1; C++ overloads: 1. Throws: AttributeNotOwned, AttributeNotDefined, ObjectInstanceNotKnown, SaveInProgress, RestoreInProgress, FederateNotExecutionMember; ….
    def attributeOwnershipReleaseDenied(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleSet) -> None: ...

    # Source: Java/C++ §7.13. Java overloads: 1; C++ overloads: 1. Throws: AttributeNotOwned, AttributeNotDefined, ObjectInstanceNotKnown, SaveInProgress, RestoreInProgress, FederateNotExecutionMember; ….
    def attributeOwnershipDivestitureIfWanted(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleSet) -> AttributeHandleSet: ...

    # Source: Java/C++ §7.14. Java overloads: 1; C++ overloads: 1. Throws: AttributeDivestitureWasNotRequested, AttributeNotOwned, AttributeNotDefined, ObjectInstanceNotKnown, SaveInProgress, RestoreInProgress; ….
    def cancelNegotiatedAttributeOwnershipDivestiture(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleSet) -> None: ...

    # Source: Java/C++ §7.15. Java overloads: 1; C++ overloads: 1. Throws: AttributeAcquisitionWasNotRequested, AttributeAlreadyOwned, AttributeNotDefined, ObjectInstanceNotKnown, SaveInProgress, RestoreInProgress; ….
    def cancelAttributeOwnershipAcquisition(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleSet) -> None: ...

    # Source: Java/C++ §7.17. Java overloads: 1; C++ overloads: 1. Throws: AttributeNotDefined, ObjectInstanceNotKnown, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected; ….
    def queryAttributeOwnership(self, theObject: ObjectInstanceHandle, theAttribute: AttributeHandle) -> None: ...

    # Source: Java/C++ §7.19. Java overloads: 1; C++ overloads: 1. Throws: AttributeNotDefined, ObjectInstanceNotKnown, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected; ….
    def isAttributeOwnedByFederate(self, theObject: ObjectInstanceHandle, theAttribute: AttributeHandle) -> bool: ...

    # Source: Java/C++ §8.2. Java overloads: 1; C++ overloads: 1. Throws: InvalidLookahead, InTimeAdvancingState, RequestForTimeRegulationPending, TimeRegulationAlreadyEnabled, SaveInProgress, RestoreInProgress; ….
    def enableTimeRegulation(self, theLookahead: LogicalTimeInterval) -> None: ...

    # Source: Java/C++ §8.4. Java overloads: 1; C++ overloads: 1. Throws: TimeRegulationIsNotEnabled, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def disableTimeRegulation(self) -> None: ...

    # Source: Java/C++ §8.5. Java overloads: 1; C++ overloads: 1. Throws: InTimeAdvancingState, RequestForTimeConstrainedPending, TimeConstrainedAlreadyEnabled, SaveInProgress, RestoreInProgress, FederateNotExecutionMember; ….
    def enableTimeConstrained(self) -> None: ...

    # Source: Java/C++ §8.7. Java overloads: 1; C++ overloads: 1. Throws: TimeConstrainedIsNotEnabled, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def disableTimeConstrained(self) -> None: ...

    # Source: Java/C++ §8.8. Java overloads: 1; C++ overloads: 1. Throws: LogicalTimeAlreadyPassed, InvalidLogicalTime, InTimeAdvancingState, RequestForTimeRegulationPending, RequestForTimeConstrainedPending, SaveInProgress; ….
    def timeAdvanceRequest(self, theTime: LogicalTime) -> None: ...

    # Source: Java/C++ §8.9. Java overloads: 1; C++ overloads: 1. Throws: LogicalTimeAlreadyPassed, InvalidLogicalTime, InTimeAdvancingState, RequestForTimeRegulationPending, RequestForTimeConstrainedPending, SaveInProgress; ….
    def timeAdvanceRequestAvailable(self, theTime: LogicalTime) -> None: ...

    # Source: Java/C++ §8.10. Java overloads: 1; C++ overloads: 1. Throws: LogicalTimeAlreadyPassed, InvalidLogicalTime, InTimeAdvancingState, RequestForTimeRegulationPending, RequestForTimeConstrainedPending, SaveInProgress; ….
    def nextMessageRequest(self, theTime: LogicalTime) -> None: ...

    # Source: Java/C++ §8.11. Java overloads: 1; C++ overloads: 1. Throws: LogicalTimeAlreadyPassed, InvalidLogicalTime, InTimeAdvancingState, RequestForTimeRegulationPending, RequestForTimeConstrainedPending, SaveInProgress; ….
    def nextMessageRequestAvailable(self, theTime: LogicalTime) -> None: ...

    # Source: Java/C++ §8.12. Java overloads: 1; C++ overloads: 1. Throws: LogicalTimeAlreadyPassed, InvalidLogicalTime, InTimeAdvancingState, RequestForTimeRegulationPending, RequestForTimeConstrainedPending, SaveInProgress; ….
    def flushQueueRequest(self, theTime: LogicalTime) -> None: ...

    # Source: Java/C++ §8.14. Java overloads: 1; C++ overloads: 1. Throws: AsynchronousDeliveryAlreadyEnabled, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def enableAsynchronousDelivery(self) -> None: ...

    # Source: Java/C++ §8.15. Java overloads: 1; C++ overloads: 1. Throws: AsynchronousDeliveryAlreadyDisabled, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def disableAsynchronousDelivery(self) -> None: ...

    # Source: Java/C++ §8.16. Java overloads: 1; C++ overloads: 1. Throws: SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def queryGALT(self) -> TimeQueryReturn: ...

    # Source: Java/C++ §8.17. Java overloads: 1; C++ overloads: 1. Throws: SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def queryLogicalTime(self) -> LogicalTime: ...

    # Source: Java/C++ §8.18. Java overloads: 1; C++ overloads: 1. Throws: SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def queryLITS(self) -> TimeQueryReturn: ...

    # Source: Java/C++ §8.19. Java overloads: 1; C++ overloads: 1. Throws: InvalidLookahead, InTimeAdvancingState, TimeRegulationIsNotEnabled, SaveInProgress, RestoreInProgress, FederateNotExecutionMember; ….
    def modifyLookahead(self, theLookahead: LogicalTimeInterval) -> None: ...

    # Source: Java/C++ §8.20. Java overloads: 1; C++ overloads: 1. Throws: TimeRegulationIsNotEnabled, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def queryLookahead(self) -> LogicalTimeInterval: ...

    # Source: Java/C++ §8.21. Java overloads: 1; C++ overloads: 1. Throws: MessageCanNoLongerBeRetracted, InvalidMessageRetractionHandle, TimeRegulationIsNotEnabled, SaveInProgress, RestoreInProgress, FederateNotExecutionMember; ….
    def retract(self, theHandle: MessageRetractionHandle) -> None: ...

    # Source: Java/C++ §8.23. Java overloads: 1; C++ overloads: 1. Throws: AttributeNotOwned, AttributeNotDefined, ObjectInstanceNotKnown, SaveInProgress, RestoreInProgress, FederateNotExecutionMember; ….
    def changeAttributeOrderType(self, theObject: ObjectInstanceHandle, theAttributes: AttributeHandleSet, theType: OrderType) -> None: ...

    # Source: Java/C++ §8.24. Java overloads: 1; C++ overloads: 1. Throws: InteractionClassNotPublished, InteractionClassNotDefined, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected; ….
    def changeInteractionOrderType(self, theClass: InteractionClassHandle, theType: OrderType) -> None: ...

    # Source: Java/C++ §9.2. Java overloads: 1; C++ overloads: 1. Throws: InvalidDimensionHandle, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def createRegion(self, dimensions: DimensionHandleSet) -> RegionHandle: ...

    # Source: Java/C++ §9.3. Java overloads: 1; C++ overloads: 1. Throws: RegionNotCreatedByThisFederate, InvalidRegion, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected; ….
    def commitRegionModifications(self, regions: RegionHandleSet) -> None: ...

    # Source: Java/C++ §9.4. Java overloads: 1; C++ overloads: 1. Throws: RegionInUseForUpdateOrSubscription, RegionNotCreatedByThisFederate, InvalidRegion, SaveInProgress, RestoreInProgress, FederateNotExecutionMember; ….
    def deleteRegion(self, theRegion: RegionHandle) -> None: ...

    # Source: Java/C++ §9.5. Java overloads: 2; C++ overloads: 2. Throws: InvalidRegionContext, RegionNotCreatedByThisFederate, InvalidRegion, AttributeNotPublished, ObjectClassNotPublished, AttributeNotDefined; ….
    @overload
    def registerObjectInstanceWithRegions(self, theClass: ObjectClassHandle, attributesAndRegions: AttributeSetRegionSetPairList) -> ObjectInstanceHandle: ...
    @overload
    def registerObjectInstanceWithRegions(self, theClass: ObjectClassHandle, attributesAndRegions: AttributeSetRegionSetPairList, theObject: str) -> ObjectInstanceHandle: ...

    # Source: Java/C++ §9.6. Java overloads: 1; C++ overloads: 1. Throws: InvalidRegionContext, RegionNotCreatedByThisFederate, InvalidRegion, AttributeNotDefined, ObjectInstanceNotKnown, SaveInProgress; ….
    def associateRegionsForUpdates(self, theObject: ObjectInstanceHandle, attributesAndRegions: AttributeSetRegionSetPairList) -> None: ...

    # Source: Java/C++ §9.7. Java overloads: 1; C++ overloads: 1. Throws: RegionNotCreatedByThisFederate, InvalidRegion, AttributeNotDefined, ObjectInstanceNotKnown, SaveInProgress, RestoreInProgress; ….
    def unassociateRegionsForUpdates(self, theObject: ObjectInstanceHandle, attributesAndRegions: AttributeSetRegionSetPairList) -> None: ...

    # Source: Java/C++ §9.8. Java overloads: 2; C++ overloads: 1. Throws: InvalidRegionContext, RegionNotCreatedByThisFederate, InvalidRegion, AttributeNotDefined, ObjectClassNotDefined, SaveInProgress; ….
    @overload
    def subscribeObjectClassAttributesWithRegions(self, theClass: ObjectClassHandle, attributesAndRegions: AttributeSetRegionSetPairList) -> None: ...
    @overload
    def subscribeObjectClassAttributesWithRegions(self, theClass: ObjectClassHandle, attributesAndRegions: AttributeSetRegionSetPairList, updateRateDesignator: str) -> None: ...

    # Source: Java §9.8. Java overloads: 2; C++ overloads: 0. Throws: InvalidRegionContext, RegionNotCreatedByThisFederate, InvalidRegion, AttributeNotDefined, ObjectClassNotDefined, SaveInProgress; ….
    @overload
    def subscribeObjectClassAttributesPassivelyWithRegions(self, theClass: ObjectClassHandle, attributesAndRegions: AttributeSetRegionSetPairList) -> None: ...
    @overload
    def subscribeObjectClassAttributesPassivelyWithRegions(self, theClass: ObjectClassHandle, attributesAndRegions: AttributeSetRegionSetPairList, updateRateDesignator: str) -> None: ...

    # Source: Java/C++ §9.9. Java overloads: 1; C++ overloads: 1. Throws: RegionNotCreatedByThisFederate, InvalidRegion, AttributeNotDefined, ObjectClassNotDefined, SaveInProgress, RestoreInProgress; ….
    def unsubscribeObjectClassAttributesWithRegions(self, theClass: ObjectClassHandle, attributesAndRegions: AttributeSetRegionSetPairList) -> None: ...

    # Source: Java/C++ §9.10. Java overloads: 1; C++ overloads: 1. Throws: FederateServiceInvocationsAreBeingReportedViaMOM, InvalidRegionContext, RegionNotCreatedByThisFederate, InvalidRegion, InteractionClassNotDefined, SaveInProgress; ….
    def subscribeInteractionClassWithRegions(self, theClass: InteractionClassHandle, regions: RegionHandleSet) -> None: ...

    # Source: Java §9.10. Java overloads: 1; C++ overloads: 0. Throws: FederateServiceInvocationsAreBeingReportedViaMOM, InvalidRegionContext, RegionNotCreatedByThisFederate, InvalidRegion, InteractionClassNotDefined, SaveInProgress; ….
    def subscribeInteractionClassPassivelyWithRegions(self, theClass: InteractionClassHandle, regions: RegionHandleSet) -> None: ...

    # Source: Java/C++ §9.11. Java overloads: 1; C++ overloads: 1. Throws: RegionNotCreatedByThisFederate, InvalidRegion, InteractionClassNotDefined, SaveInProgress, RestoreInProgress, FederateNotExecutionMember; ….
    def unsubscribeInteractionClassWithRegions(self, theClass: InteractionClassHandle, regions: RegionHandleSet) -> None: ...

    # Source: Java/C++ §9.12. Java overloads: 2; C++ overloads: 2. Throws: InvalidRegionContext, RegionNotCreatedByThisFederate, InvalidRegion, InteractionClassNotPublished, InteractionParameterNotDefined, InteractionClassNotDefined; ….
    @overload
    def sendInteractionWithRegions(self, theInteraction: InteractionClassHandle, theParameters: ParameterHandleValueMap, regions: RegionHandleSet, userSuppliedTag: bytes) -> None: ...
    @overload
    def sendInteractionWithRegions(self, theInteraction: InteractionClassHandle, theParameters: ParameterHandleValueMap, regions: RegionHandleSet, userSuppliedTag: bytes, theTime: LogicalTime) -> MessageRetractionReturn: ...

    # Source: Java/C++ §9.13. Java overloads: 1; C++ overloads: 1. Throws: InvalidRegionContext, RegionNotCreatedByThisFederate, InvalidRegion, AttributeNotDefined, ObjectClassNotDefined, SaveInProgress; ….
    def requestAttributeValueUpdateWithRegions(self, theClass: ObjectClassHandle, attributesAndRegions: AttributeSetRegionSetPairList, userSuppliedTag: bytes) -> None: ...

    # Source: Java/C++ §10.2. Java overloads: 1; C++ overloads: 1. Throws: FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getAutomaticResignDirective(self) -> ResignAction: ...

    # Source: Java/C++ §10.3. Java overloads: 1; C++ overloads: 1. Throws: InvalidResignAction, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def setAutomaticResignDirective(self, resignAction: ResignAction) -> None: ...

    # Source: Java/C++ §10.4. Java overloads: 1; C++ overloads: 1. Throws: NameNotFound, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getFederateHandle(self, theName: str) -> FederateHandle: ...

    # Source: Java/C++ §10.5. Java overloads: 1; C++ overloads: 1. Throws: InvalidFederateHandle, FederateHandleNotKnown, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getFederateName(self, theHandle: FederateHandle) -> str: ...

    # Source: Java/C++ §10.6. Java overloads: 1; C++ overloads: 1. Throws: NameNotFound, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getObjectClassHandle(self, theName: str) -> ObjectClassHandle: ...

    # Source: Java/C++ §10.7. Java overloads: 1; C++ overloads: 1. Throws: InvalidObjectClassHandle, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getObjectClassName(self, theHandle: ObjectClassHandle) -> str: ...

    # Source: Java/C++ §10.8. Java overloads: 1; C++ overloads: 1. Throws: ObjectInstanceNotKnown, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getKnownObjectClassHandle(self, theObject: ObjectInstanceHandle) -> ObjectClassHandle: ...

    # Source: Java/C++ §10.9. Java overloads: 1; C++ overloads: 1. Throws: ObjectInstanceNotKnown, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getObjectInstanceHandle(self, theName: str) -> ObjectInstanceHandle: ...

    # Source: Java/C++ §10.10. Java overloads: 1; C++ overloads: 1. Throws: ObjectInstanceNotKnown, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getObjectInstanceName(self, theHandle: ObjectInstanceHandle) -> str: ...

    # Source: Java/C++ §10.11. Java overloads: 1; C++ overloads: 1. Throws: NameNotFound, InvalidObjectClassHandle, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getAttributeHandle(self, whichClass: ObjectClassHandle, theName: str) -> AttributeHandle: ...

    # Source: Java/C++ §10.12. Java overloads: 1; C++ overloads: 1. Throws: AttributeNotDefined, InvalidAttributeHandle, InvalidObjectClassHandle, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getAttributeName(self, whichClass: ObjectClassHandle, theHandle: AttributeHandle) -> str: ...

    # Source: Java/C++ §10.13. Java overloads: 1; C++ overloads: 1. Throws: InvalidUpdateRateDesignator, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getUpdateRateValue(self, updateRateDesignator: str) -> float: ...

    # Source: Java/C++ §10.14. Java overloads: 1; C++ overloads: 1. Throws: ObjectInstanceNotKnown, AttributeNotDefined, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getUpdateRateValueForAttribute(self, theObject: ObjectInstanceHandle, theAttribute: AttributeHandle) -> float: ...

    # Source: Java/C++ §10.15. Java overloads: 1; C++ overloads: 1. Throws: NameNotFound, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getInteractionClassHandle(self, theName: str) -> InteractionClassHandle: ...

    # Source: Java/C++ §10.16. Java overloads: 1; C++ overloads: 1. Throws: InvalidInteractionClassHandle, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getInteractionClassName(self, theHandle: InteractionClassHandle) -> str: ...

    # Source: Java/C++ §10.17. Java overloads: 1; C++ overloads: 1. Throws: NameNotFound, InvalidInteractionClassHandle, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getParameterHandle(self, whichClass: InteractionClassHandle, theName: str) -> ParameterHandle: ...

    # Source: Java/C++ §10.18. Java overloads: 1; C++ overloads: 1. Throws: InteractionParameterNotDefined, InvalidParameterHandle, InvalidInteractionClassHandle, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getParameterName(self, whichClass: InteractionClassHandle, theHandle: ParameterHandle) -> str: ...

    # Source: Java/C++ §10.19. Java overloads: 1; C++ overloads: 1. Throws: InvalidOrderName, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getOrderType(self, theName: str) -> OrderType: ...

    # Source: Java/C++ §10.20. Java overloads: 1; C++ overloads: 1. Throws: InvalidOrderType, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getOrderName(self, theType: OrderType) -> str: ...

    # Source: Java §10.21. Java overloads: 1; C++ overloads: 0. Throws: InvalidTransportationName, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getTransportationTypeHandle(self, theName: str) -> TransportationTypeHandle: ...

    # Source: Java §10.22. Java overloads: 1; C++ overloads: 0. Throws: InvalidTransportationType, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getTransportationTypeName(self, theHandle: TransportationTypeHandle) -> str: ...

    # Source: Java/C++ §10.23. Java overloads: 1; C++ overloads: 1. Throws: AttributeNotDefined, InvalidAttributeHandle, InvalidObjectClassHandle, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getAvailableDimensionsForClassAttribute(self, whichClass: ObjectClassHandle, theHandle: AttributeHandle) -> DimensionHandleSet: ...

    # Source: Java/C++ §10.24. Java overloads: 1; C++ overloads: 1. Throws: InvalidInteractionClassHandle, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getAvailableDimensionsForInteractionClass(self, theHandle: InteractionClassHandle) -> DimensionHandleSet: ...

    # Source: Java/C++ §10.25. Java overloads: 1; C++ overloads: 1. Throws: NameNotFound, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getDimensionHandle(self, theName: str) -> DimensionHandle: ...

    # Source: Java/C++ §10.26. Java overloads: 1; C++ overloads: 1. Throws: InvalidDimensionHandle, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getDimensionName(self, theHandle: DimensionHandle) -> str: ...

    # Source: Java/C++ §10.27. Java overloads: 1; C++ overloads: 1. Throws: InvalidDimensionHandle, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getDimensionUpperBound(self, theHandle: DimensionHandle) -> int: ...

    # Source: Java/C++ §10.28. Java overloads: 1; C++ overloads: 1. Throws: InvalidRegion, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getDimensionHandleSet(self, region: RegionHandle) -> DimensionHandleSet: ...

    # Source: Java/C++ §10.29. Java overloads: 1; C++ overloads: 1. Throws: RegionDoesNotContainSpecifiedDimension, InvalidRegion, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected; ….
    def getRangeBounds(self, region: RegionHandle, dimension: DimensionHandle) -> RangeBounds: ...

    # Source: Java/C++ §10.30. Java overloads: 1; C++ overloads: 1. Throws: InvalidRangeBound, RegionDoesNotContainSpecifiedDimension, RegionNotCreatedByThisFederate, InvalidRegion, SaveInProgress, RestoreInProgress; ….
    def setRangeBounds(self, region: RegionHandle, dimension: DimensionHandle, bounds: RangeBounds) -> None: ...

    # Source: Java/C++ §10.31. Java overloads: 1; C++ overloads: 1. Throws: InvalidFederateHandle, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def normalizeFederateHandle(self, federateHandle: FederateHandle) -> int: ...

    # Source: Java/C++ §10.32. Java overloads: 1; C++ overloads: 1. Throws: InvalidServiceGroup, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def normalizeServiceGroup(self, group: ServiceGroup) -> int: ...

    # Source: Java/C++ §10.33. Java overloads: 1; C++ overloads: 1. Throws: ObjectClassRelevanceAdvisorySwitchIsOn, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def enableObjectClassRelevanceAdvisorySwitch(self) -> None: ...

    # Source: Java/C++ §10.34. Java overloads: 1; C++ overloads: 1. Throws: ObjectClassRelevanceAdvisorySwitchIsOff, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def disableObjectClassRelevanceAdvisorySwitch(self) -> None: ...

    # Source: Java/C++ §10.35. Java overloads: 1; C++ overloads: 1. Throws: AttributeRelevanceAdvisorySwitchIsOn, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def enableAttributeRelevanceAdvisorySwitch(self) -> None: ...

    # Source: Java/C++ §10.36. Java overloads: 1; C++ overloads: 1. Throws: AttributeRelevanceAdvisorySwitchIsOff, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def disableAttributeRelevanceAdvisorySwitch(self) -> None: ...

    # Source: Java/C++ §10.37. Java overloads: 1; C++ overloads: 1. Throws: AttributeScopeAdvisorySwitchIsOn, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def enableAttributeScopeAdvisorySwitch(self) -> None: ...

    # Source: Java/C++ §10.38. Java overloads: 1; C++ overloads: 1. Throws: AttributeScopeAdvisorySwitchIsOff, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def disableAttributeScopeAdvisorySwitch(self) -> None: ...

    # Source: Java/C++ §10.39. Java overloads: 1; C++ overloads: 1. Throws: InteractionRelevanceAdvisorySwitchIsOn, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def enableInteractionRelevanceAdvisorySwitch(self) -> None: ...

    # Source: Java/C++ §10.40. Java overloads: 1; C++ overloads: 1. Throws: InteractionRelevanceAdvisorySwitchIsOff, SaveInProgress, RestoreInProgress, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def disableInteractionRelevanceAdvisorySwitch(self) -> None: ...

    # Source: Java/C++ §10.41. Java overloads: 1; C++ overloads: 1. Throws: CallNotAllowedFromWithinCallback, RTIinternalError.
    def evokeCallback(self, approximateMinimumTimeInSeconds: float) -> bool: ...

    # Source: Java/C++ §10.42. Java overloads: 1; C++ overloads: 1. Throws: CallNotAllowedFromWithinCallback, RTIinternalError.
    def evokeMultipleCallbacks(self, approximateMinimumTimeInSeconds: float, approximateMaximumTimeInSeconds: float) -> bool: ...

    # Source: Java/C++ §10.43. Java overloads: 1; C++ overloads: 1. Throws: SaveInProgress, RestoreInProgress, RTIinternalError.
    def enableCallbacks(self) -> None: ...

    # Source: Java/C++ §10.44. Java overloads: 1; C++ overloads: 1. Throws: SaveInProgress, RestoreInProgress, RTIinternalError.
    def disableCallbacks(self) -> None: ...

    # Source: Java API-specific services. Java overloads: 1; C++ overloads: 0. Throws: FederateNotExecutionMember, NotConnected.
    def getAttributeHandleFactory(self) -> AttributeHandleFactory: ...

    # Source: Java API-specific services. Java overloads: 1; C++ overloads: 0. Throws: FederateNotExecutionMember, NotConnected.
    def getAttributeHandleSetFactory(self) -> AttributeHandleSetFactory: ...

    # Source: Java API-specific services. Java overloads: 1; C++ overloads: 0. Throws: FederateNotExecutionMember, NotConnected.
    def getAttributeHandleValueMapFactory(self) -> AttributeHandleValueMapFactory: ...

    # Source: Java API-specific services. Java overloads: 1; C++ overloads: 0. Throws: FederateNotExecutionMember, NotConnected.
    def getAttributeSetRegionSetPairListFactory(self) -> AttributeSetRegionSetPairListFactory: ...

    # Source: Java API-specific services. Java overloads: 1; C++ overloads: 0. Throws: FederateNotExecutionMember, NotConnected.
    def getDimensionHandleFactory(self) -> DimensionHandleFactory: ...

    # Source: Java API-specific services. Java overloads: 1; C++ overloads: 0. Throws: FederateNotExecutionMember, NotConnected.
    def getDimensionHandleSetFactory(self) -> DimensionHandleSetFactory: ...

    # Source: Java API-specific services. Java overloads: 1; C++ overloads: 0. Throws: FederateNotExecutionMember, NotConnected.
    def getFederateHandleFactory(self) -> FederateHandleFactory: ...

    # Source: Java API-specific services. Java overloads: 1; C++ overloads: 0. Throws: FederateNotExecutionMember, NotConnected.
    def getFederateHandleSetFactory(self) -> FederateHandleSetFactory: ...

    # Source: Java API-specific services. Java overloads: 1; C++ overloads: 0. Throws: FederateNotExecutionMember, NotConnected.
    def getInteractionClassHandleFactory(self) -> InteractionClassHandleFactory: ...

    # Source: Java API-specific services. Java overloads: 1; C++ overloads: 0. Throws: FederateNotExecutionMember, NotConnected.
    def getObjectClassHandleFactory(self) -> ObjectClassHandleFactory: ...

    # Source: Java API-specific services. Java overloads: 1; C++ overloads: 0. Throws: FederateNotExecutionMember, NotConnected.
    def getObjectInstanceHandleFactory(self) -> ObjectInstanceHandleFactory: ...

    # Source: Java API-specific services. Java overloads: 1; C++ overloads: 0. Throws: FederateNotExecutionMember, NotConnected.
    def getParameterHandleFactory(self) -> ParameterHandleFactory: ...

    # Source: Java API-specific services. Java overloads: 1; C++ overloads: 0. Throws: FederateNotExecutionMember, NotConnected.
    def getParameterHandleValueMapFactory(self) -> ParameterHandleValueMapFactory: ...

    # Source: Java API-specific services. Java overloads: 1; C++ overloads: 0. Throws: FederateNotExecutionMember, NotConnected.
    def getRegionHandleSetFactory(self) -> RegionHandleSetFactory: ...

    # Source: Java API-specific services. Java overloads: 1; C++ overloads: 0. Throws: FederateNotExecutionMember, NotConnected.
    def getTransportationTypeHandleFactory(self) -> TransportationTypeHandleFactory: ...

    # Source: Java API-specific services. Java overloads: 1; C++ overloads: 0.
    def getHLAversion(self) -> str: ...

    # Source: Java/C++ API-specific services. Java overloads: 1; C++ overloads: 1. Throws: FederateNotExecutionMember, NotConnected.
    def getTimeFactory(self) -> LogicalTimeFactory: ...

    # Source: C++ §4.5. Java overloads: 0; C++ overloads: 1. Throws: CouldNotCreateLogicalTimeFactory, InconsistentFDD, ErrorReadingFDD, CouldNotOpenFDD, DesignatorIsHLAstandardMIM, ErrorReadingMIM; ….
    @overload
    def createFederationExecutionWithMIM(self, federationExecutionName: str, fomModules: Sequence[str], mimModule: str) -> None: ...
    @overload
    def createFederationExecutionWithMIM(self, federationExecutionName: str, fomModules: Sequence[str], mimModule: str, logicalTimeImplementationName: str) -> None: ...

    # Source: C++ §10.21. Java overloads: 0; C++ overloads: 1. Throws: InvalidTransportationName, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getTransportationType(self, transportationName: str) -> TransportationType: ...

    # Source: C++ §10.22. Java overloads: 0; C++ overloads: 1. Throws: InvalidTransportationType, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def getTransportationName(self, transportationType: TransportationType) -> str: ...

    # Source: C++ Decode handles. Java overloads: 0; C++ overloads: 1. Throws: CouldNotDecode, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def decodeFederateHandle(self, encodedValue: bytes) -> FederateHandle: ...

    # Source: C++ Decode handles. Java overloads: 0; C++ overloads: 1. Throws: CouldNotDecode, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def decodeObjectClassHandle(self, encodedValue: bytes) -> ObjectClassHandle: ...

    # Source: C++ Decode handles. Java overloads: 0; C++ overloads: 1. Throws: CouldNotDecode, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def decodeInteractionClassHandle(self, encodedValue: bytes) -> InteractionClassHandle: ...

    # Source: C++ Decode handles. Java overloads: 0; C++ overloads: 1. Throws: CouldNotDecode, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def decodeObjectInstanceHandle(self, encodedValue: bytes) -> ObjectInstanceHandle: ...

    # Source: C++ Decode handles. Java overloads: 0; C++ overloads: 1. Throws: CouldNotDecode, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def decodeAttributeHandle(self, encodedValue: bytes) -> AttributeHandle: ...

    # Source: C++ Decode handles. Java overloads: 0; C++ overloads: 1. Throws: CouldNotDecode, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def decodeParameterHandle(self, encodedValue: bytes) -> ParameterHandle: ...

    # Source: C++ Decode handles. Java overloads: 0; C++ overloads: 1. Throws: CouldNotDecode, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def decodeDimensionHandle(self, encodedValue: bytes) -> DimensionHandle: ...

    # Source: C++ Decode handles. Java overloads: 0; C++ overloads: 1. Throws: CouldNotDecode, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def decodeMessageRetractionHandle(self, encodedValue: bytes) -> MessageRetractionHandle: ...

    # Source: C++ Decode handles. Java overloads: 0; C++ overloads: 1. Throws: CouldNotDecode, FederateNotExecutionMember, NotConnected, RTIinternalError.
    def decodeRegionHandle(self, encodedValue: bytes) -> RegionHandle: ...
