# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: HLA2025RTITransport.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'HLA2025RTITransport.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19HLA2025RTITransport.proto\x12\x13rti1516_2025.fedpro\x1a\x18RTIambassador_2025.proto\x1a\x1d\x46\x65\x64\x65rateAmbassador_2025.proto2\xc1\x01\n\x14HLA2025FedProGateway\x12K\n\x04\x43\x61ll\x12 .rti1516_2025.fedpro.CallRequest\x1a!.rti1516_2025.fedpro.CallResponse\x12\\\n\rEvokeCallback\x12%.rti1516_2025.fedpro.CallbackResponse\x1a$.rti1516_2025.fedpro.CallbackRequestB\x1b\n\x17hla.rti1516_2025.fedproP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HLA2025RTITransport_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027hla.rti1516_2025.fedproP\001'
  _globals['_HLA2025FEDPROGATEWAY']._serialized_start=108
  _globals['_HLA2025FEDPROGATEWAY']._serialized_end=301
# @@protoc_insertion_point(module_scope)
