"""Retired shim backend module kept only to preserve importability during migration."""

from __future__ import annotations

from hla.backends.python1516_2025.backend import (
    MOM_2025_FEDERATE_ADJUST_LEAVES,
    MOM_2025_FEDERATE_REQUEST_LEAVES,
    MOM_2025_FEDERATE_SERVICE_LEAVES,
    MOM_2025_FEDERATION_ADJUST_LEAVES,
    MOM_2025_FEDERATION_REQUEST_LEAVES,
    MOM_2025_INPROCESS_ROUTED_MANAGER_LEAVES,
)

__all__ = [
    "MOM_2025_FEDERATE_ADJUST_LEAVES",
    "MOM_2025_FEDERATE_REQUEST_LEAVES",
    "MOM_2025_FEDERATE_SERVICE_LEAVES",
    "MOM_2025_FEDERATION_ADJUST_LEAVES",
    "MOM_2025_FEDERATION_REQUEST_LEAVES",
    "MOM_2025_INPROCESS_ROUTED_MANAGER_LEAVES",
]
