# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hla.transports.grpc.fedpro2010 import FederateAmbassador_pb2 as FederateAmbassador__pb2
from hla.transports.grpc.fedpro2010 import RTIambassador_pb2 as RTIambassador__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in HLA2010RTITransport_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HLA2010FedProGatewayStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/rti1516e.fedpro.HLA2010FedProGateway/Call',
                request_serializer=RTIambassador__pb2.CallRequest.SerializeToString,
                response_deserializer=RTIambassador__pb2.CallResponse.FromString,
                _registered_method=True)
        self.EvokeCallback = channel.unary_unary(
                '/rti1516e.fedpro.HLA2010FedProGateway/EvokeCallback',
                request_serializer=FederateAmbassador__pb2.CallbackResponse.SerializeToString,
                response_deserializer=FederateAmbassador__pb2.CallbackRequest.FromString,
                _registered_method=True)


class HLA2010FedProGatewayServicer:
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvokeCallback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HLA2010FedProGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=RTIambassador__pb2.CallRequest.FromString,
                    response_serializer=RTIambassador__pb2.CallResponse.SerializeToString,
            ),
            'EvokeCallback': grpc.unary_unary_rpc_method_handler(
                    servicer.EvokeCallback,
                    request_deserializer=FederateAmbassador__pb2.CallbackResponse.FromString,
                    response_serializer=FederateAmbassador__pb2.CallbackRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rti1516e.fedpro.HLA2010FedProGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rti1516e.fedpro.HLA2010FedProGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HLA2010FedProGateway:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rti1516e.fedpro.HLA2010FedProGateway/Call',
            RTIambassador__pb2.CallRequest.SerializeToString,
            RTIambassador__pb2.CallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvokeCallback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rti1516e.fedpro.HLA2010FedProGateway/EvokeCallback',
            FederateAmbassador__pb2.CallbackResponse.SerializeToString,
            FederateAmbassador__pb2.CallbackRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
