# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: HLA2010RTITransport.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'HLA2010RTITransport.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19HLA2010RTITransport.proto\x12\x0frti1516e.fedpro\x1a\x13RTIambassador.proto\x1a\x18\x46\x65\x64\x65rateAmbassador.proto2\xb1\x01\n\x14HLA2010FedProGateway\x12\x43\n\x04\x43\x61ll\x12\x1c.rti1516e.fedpro.CallRequest\x1a\x1d.rti1516e.fedpro.CallResponse\x12T\n\rEvokeCallback\x12!.rti1516e.fedpro.CallbackResponse\x1a .rti1516e.fedpro.CallbackRequestB\x17\n\x13hla.rti1516e.fedproP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HLA2010RTITransport_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023hla.rti1516e.fedproP\001'
  _globals['_HLA2010FEDPROGATEWAY']._serialized_start=94
  _globals['_HLA2010FEDPROGATEWAY']._serialized_end=271
# @@protoc_insertion_point(module_scope)
